### ISSUE TITLE
提议：把剪辑后的音频 review 过程放到一个私有 repo 里做 review

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#109]
目前，我们 review 剪辑后的音频的过程做的不够公开、透明，但是，为了避免有不合适发布的内容被大范围传播，我提议创建一个私有 repo 来做 review。具体如下：

* 创建名为 `audio-review` 的 repo（或其他名称）
* 每次剪辑完成后，创建一个 issue 来跟踪 review 过程
* 避免没人 review 的情况而无限延期发布，review deadline 为一周，时间截止后即认为可以发布

其他好处：

* 把 review 过程放到 GitHub 中，orbit 就可以方便统计到大家的付出

**Comment by wey-gu** [comment]
it's feasible to me, maybe media-review/content-review?

**Comment by LinuxSuRen** [comment]
`content-review` is better.

**Comment by LinuxSuRen** [comment]
I have tested a private team which is a sub-team of @opensource-f2f/guest . That means all guests of this program be able to do the review work.

Please let the admin team @opensource-f2f/admin know if you anyone willing to help us to do the review work.

But please remember that we need to keep it be private before we believe it can be published.

**Comment by LinuxSuRen** [comment]
欢迎有兴趣的朋友们帮忙 review
