### ISSUE TITLE
18个技术类播客致广大听友的一份邀请函

### ISSUE THREAD

**Issue by le0zh0u** [opensource-f2f/episode#118]
平等、公开、透明的活动总是能让每一位参与者都人尽其才并得到相应的收获，这次的“技术播客月”活动，不仅仅是有那些愿意在活动筹划、组织阶段就参与进来的小伙伴，我们也特别希望能够听到来自最广大的听友的声音！

如果你有在听以下的任意一档节目，非常欢迎留言给我们你想听的话题。你提交的话题有机会作为本次技术播客月活动的主题之一，甚至，可能会作为你所关注播客的某一期节目的部分内容。

参与方式，是在下面提交评论
**推荐的留言格式：播客节目名 + 话题 + 理由**

- [ALC Beijing](https://www.xiaoyuzhoufm.com/podcast/5f116a8f6d76607427ca7c47) —— 通过分享Apache本土社群的开源成功故事，致力于帮助开源爱好者更好得参与开源。
- [CHAOSScast China](https://www.xiaoyuzhoufm.com/podcast/6239354dc39130b3d9e01e44) —— 一切与繁荣开源软件社区，度量分析，促进社区多样、平等和包容相关的话题
- [Emacs Talk](https://emacstalk.github.io/podcast/) —— EmacsTalk 是一档专注在 Emacs 社区的程序员闲聊节目
- [Go 夜聊](https://talkgo.fm/) —— 「Go 夜聊」是一档由杨文和欧长坤主持的针对 Go 语言发展史的播客节目。我们的宗旨是让更多的人了解 Go 语言的发展历史和未来规划，希望大家在这里可以了解到 Go 语言的方方面面。
- [Nebula Graph 星球](https://www.ximalaya.com/album/54212026) ——  一个聊开源、图技术分布式系统和有趣故事的星球，随时在 b612 等你拜访
- [OnBoard](https://www.xiaoyuzhoufm.com/podcast/61cbaac48bb4cd867fcabe22) —— 来自一线的投资思考，聊聊软件如何改变世界
- [Web Worker](https://www.xiaoyuzhoufm.com/podcast/613753ef23c82a9a1ccfdf35) —— 几个前端程序员闲聊的音频播客节目
- [大话开源](https://www.xiaoyuzhoufm.com/podcast/61a0a44c979a88215f7fecca) —— 专注于沉淀开源人的所思所行，力求摸索出有趣、有料、有品的「开源武林秘笈」
- [编码人声](https://dao.fm/%E7%BC%96%E7%A0%81%E4%BA%BA%E5%A3%B0/) —— 编码人声是一档聚焦程序员成长的播客节目，由资深程序员和年轻开发者共同担任主播。邀请不同背景的程序员担任节目嘉宾，分享程序员职业成长、个人成长经验，为程序员听友答疑解惑。
- [科技零食](https://www.xiaoyuzhoufm.com/podcast/60955cd05ec7306b29158abd) —— 科技零食是一档由Zhaoyu和Huaming主持，对科技行业进行商业评论的播客节目
- [科技乱炖](https://dao.fm/%e4%b9%b1%e7%82%96%e6%96%b0%e9%b2%9c%e4%ba%8b%e5%84%bf/) —— 科技资讯点评播客，嬉笑怒骂之间，把近期科技热点变成犀利、独到、深刻的独家观点
- [开源面对面](https://github.com/opensource-f2f/episode) —— 面向所有开源参与者的一档访谈节目
- [后互联网时代的乱弹](https://www.xiaoyuzhoufm.com/podcast/6252b281d32de5100e54352d)——一帮老友，一起聊聊科技、未来与人
- [质量三人行](https://qapodcast.typlog.io/) —— 质量三人行是一款来自Thoughtworks（思特沃克）的播客节目，我们关注软件行业测试领域的现状和未来，质量和测试人员的职业发展。
- [陪你看开源](https://www.xiaoyuzhoufm.com/podcast/6286388483ddae2d9e72a79d) —— 是由开源社发起的一档泛文化类播客，每期精选一本开源书籍，与嘉宾畅聊，带您了解开源文化，遨游开源世界。让我们从一本开源之书开始旅程！
- [枫言枫语](https://www.xiaoyuzhoufm.com/podcast/5e2864f5418a84a04628e249) —— 听见科技与人文的声音。这是一档由开发者 @枫影JustinYan 和 设计师 @自力hzlzh 主持的播客节目
- [一派·Podcast](https://sspai.typlog.io/) —— 少数派旗下播客节目，高效工作，品质生活

如果你喜欢某个话题，可以在Comment下添加互动emoji表情，给话题加一点power。
我们会观察听友的留言话题下的互动emoji表情数量，排名前十的话题，将会奖励合作社区的周边礼品。
活动截止时间：6月30日 24:00

合作社区：ALC Beijing、freeCodeCamp、JuiceFS、KubeSphere、Nebula Graph、OpenMLDB、RTC开发者社区、StreamNative、大话开源、极狐、开源社。
合作平台：CSDN、OSCHINA、segmentfault 思否、活动行、少数派、小宇宙
合作企业：津津乐道播客网络

> 本提议来自 freeCodeCamp 的 Miya，并受到活动共建方的支持，感谢每一位活动共建者！

[邀请函原文地址](https://rkawrngf0e.feishu.cn/docs/doccn8R6xBVrcHMVYiVgq4Rds7d)

**Comment by zhangchao-wooc** [comment]
**Web Worker**

聊一聊遇到的转行的程序员🦧

经常会看到一些话题：‘怎么筛选掉培训转行的程序员😷’。但我遇到的一些转行的或者培训出来的人其实都很有想法，思路清晰，甚至比所谓的名校出来的人还要优秀，当然了也有一些摆烂的。想听听大家都有什么想法或者身边人有类似的经历👀？

**Comment by Kaiyiwing** [comment]
**Web Worker**

生活中的程序员 / 大佬遇到过的困难 / 大佬失败的一面

我们大多只了解的技术圈大佬技术和项目强的一面，总会觉得大佬很有距离感。 但实际上很多大佬在非技术的生活上也很有趣，甚至很多大佬也经历过很多很艰难的时间，也有很多次失败的经历。我觉得可以邀请一下大佬去分享自己的生活的其他侧面（fun fact about me）、自己经历过困难、自己做的失败的一些事。我个人觉得大佬只是 努力/幸运/坚持 的普通人，通过分享这些故事可以让更多的听众更深入的了解大佬，也会激励一些人 “看起来我再努力一下也能成为大佬”  🎉🎉🎉

**Comment by Yansufeng** [comment]
**Web Worker**

关于大佬们的书单

发现身边的一些大佬桌上的书很多是一开始一些技术工具类书，然后是一些底层的理论的书，再逐渐就开始变成金融的哲学的奇奇怪怪的书🤣；
感觉偶尔静下心来看几本有意思的书也很有必要吧；
而且其实技术类的知识从网络上获取其实更便利一些，看有时候大佬看的书一些历史向的带思辨的书也很有趣！可能这就是为啥别人是大佬吧🌚。但自己书圈也拓不开，想看看大家平时都看些什么有意思的书。

**Comment by Esther-Guo** [comment]
Web Worker

前端程序员发展路线 / 想要专攻的话都有哪些方向可以选择
&&
实习生相关话题（试错期应该注重提升自己的哪些能力or认知 / 工作中的易踩雷区 / ……）

实习了三个月，每天基本都在参考mentor的代码做需求，除了偶尔能借业务复习几个知识点，其他时间基本是个CV工程师，自己学习的时间被大大压缩了🤦‍♀️ 对于未来的职业道路发展有一些方向选择上的疑惑，希望Otto和刘威前辈可以给出一些建议～🥰

**Comment by DunyuSong** [comment]
零基础转行测试开发
我是学医的，做测试之前，我尝试过很多工作，例如医院康复治疗技师、西餐厅、销售什么的，工资两千出头，因为找不到职业方向一直各个职业摸索、心情抑郁的状态持续了4年，之后才转到做测试，我比其他人坎坷，第一份工作还被辞退了，还好顺利找到了第二份工作，后来自己慢慢一步一步的从小白做到测试开发，努力了4年，天天宅在家学习，除了参与技术沙龙我都不出门的那种，各种找大佬学习，能进到一个比较好的公司去突破我在小公司没成长的困境，也是因为大佬的帮助。
我朋友们都觉得我的经历特别适合分享，但我文笔不好，就从来没有写出来过，我想问下有哪个节目有兴趣邀请我为嘉宾？（我自己不太确定我的故事适合哪个节目～）

**Comment by wey-gu** [comment]
> 零基础转行测试开发
> 
> 我是学医的，做测试之前，我尝试过很多工作，例如医院康复治疗技师、西餐厅、销售什么的，工资两千出头，因为找不到职业方向一直各个职业摸索、心情抑郁的状态持续了4年，之后才转到做测试，我比其他人坎坷，第一份工作还被辞退了，还好顺利找到了第二份工作，后来自己慢慢一步一步的从小白做到测试开发，努力了4年，天天宅在家学习，除了参与技术沙龙我都不出门的那种，各种找大佬学习，能进到一个比较好的公司去突破我在小公司没成长的困境，也是因为大佬的帮助。
> 
> 我朋友们都觉得我的经历特别适合分享，但我文笔不好，就从来没有写出来过，我想问下有哪个节目有兴趣邀请我为嘉宾？（我自己不太确定我的故事适合哪个节目～）

@DunyuSong 我们 Nebula Graph 星球对你的经历非常感兴趣，想邀请来聊聊你的成长和思考，不知道是否愿意呢？

**Comment by zhangchao-wooc** [comment]
> > 零基础转行测试开发
> > 我是一直以来的，因为我尝试过职业治疗师、餐厅、医院的两次测试，薪水的，想不出有什么治疗方法可以进行职业测试，取得治疗效果4年之后我才去做测试，我比其他人坎裁减，第一份工作被辞退了，还顺利找到了第二份工作，然后自己慢慢一步的从小白做测试开发，努力了4年，除了参加技术沙龙我出门的每一天都是这样，因为各种找大佬学习，比较能突破我在小公司成长的困境，大佬的帮助。
> > 我的朋友们都觉得我的经历特别适合分享，但我文笔不好，就从来没有写过，我想问下有没有哪位嘉宾有兴趣参加我的节目？ ～）
> 
> @DunyuSong星云星球对你曾经非常喜欢的图，想邀请来聊聊你的成长和思考，不知道我们是否愿意呢？



> 零基础 是医的，做测试的，我尝试过现场测试的，西餐厅开发的，很多工作的，工资两千的，因为我找不到专业的职业，所以需要先试出什么职业试试测试，心情压抑的持续状态持续了4年，之后才还去做测试，我比其他人的剪裁小了，第一个工作被辞退了，好顺利的找到第二份工作，然后自己慢慢从白做测试了4年，天天在家找各种工作去学习，除了技术沙我没有出门的学习，能进到一个比较好的公司突破我在小公司的成长的困境，也是因为大佬的 帮助。我现在确定我的故事适合哪个节目～）

我在第一个话题中希望可以聊聊转行程序员相关的原因就是，我就是一个转行的程序员。你是医学转行，而我是音乐学转前端开发👶

**Comment by wey-gu** [comment]
> 

啊，我才看到，太酷了，其实我也是。@zhangchao-wooc @DunyuSong  我们一起聊聊吧！

**Comment by zhangchao-wooc** [comment]
> > 我在第一个话题中希望可以聊聊转行程序员相关的原因就是，我就是一个转行的程序员。你是医学转行，而我是音乐学转前端开发👶
> 
> 啊，我才看到，太酷了，其实我也是。@zhangchao-wooc @DunyuSong 我们一起聊聊吧！

好的呀！

**Comment by wey-gu** [comment]
> > > 我在第一个话题中希望可以聊聊转行程序员相关的原因就是，我就是一个转行的程序员。你是医学转行，而我是音乐学转前端开发👶
> > 
> > 
> > 啊，我才看到，太酷了，其实我也是。@zhangchao-wooc @DunyuSong 我们一起聊聊吧！
> 
> 好的呀！

太棒了，您是嘉宾还是 host 哈？可以加我的微信我们详细聊么？我的微信id是

```bash
echo c2l2dmVpCg== | base64 -d
```
cc @DunyuSong @Hera-han

**Comment by MikeyWei** [comment]
> 零基础转行测试开发
> 我是学医的，做测试之前，我尝试过很多工作，例如医院康复治疗技师、西餐厅、销售什么的，工资两千出头，因为找不到职业方向一直各个职业摸索、心情抑郁的状态持续了4年，之后才转到做测试，我比其他人坎坷，第一份工作还被辞退了，还好顺利找到了第二份工作，后来自己慢慢一步一步的从小白做到测试开发，努力了4年，天天宅在家学习，除了参与技术沙龙我都不出门的那种，各种找大佬学习，能进到一个比较好的公司去突破我在小公司没成长的困境，也是因为大佬的帮助。
> 我朋友们都觉得我的经历特别适合分享，但我文笔不好，就从来没有写出来过，我想问下有哪个节目有兴趣邀请我为嘉宾？（我自己不太确定我的故事适合哪个节目～）

算我一个，我可以贡献点“采访大纲”方面的内容。

**Comment by wey-gu** [comment]
> > 零基础转行测试开发
> > 我是学医的，做测试之前，我尝试过很多工作，例如医院康复治疗技师、西餐厅、销售什么的，工资两千出头，因为找不到职业方向一直各个职业摸索、心情抑郁的状态持续了4年，之后才转到做测试，我比其他人坎坷，第一份工作还被辞退了，还好顺利找到了第二份工作，后来自己慢慢一步一步的从小白做到测试开发，努力了4年，天天宅在家学习，除了参与技术沙龙我都不出门的那种，各种找大佬学习，能进到一个比较好的公司去突破我在小公司没成长的困境，也是因为大佬的帮助。
> > 我朋友们都觉得我的经历特别适合分享，但我文笔不好，就从来没有写出来过，我想问下有哪个节目有兴趣邀请我为嘉宾？（我自己不太确定我的故事适合哪个节目～）
> 
> 算我一个，我可以贡献点“采访大纲”方面的内容。

太棒了👍🏻

**Comment by Otto-J** [comment]
@zhangchao-wooc @Kaiyiwing @yuemeng200 @Yansufeng @Esther-Guo 各位带给我惊喜！我们搞一期圆桌讨论吧，这些问题主播资历也浅回答得不够全面，但我可以多请几个朋友一起来回答这些问题！如果你有敬仰的前辈或者自己乐意分享请告诉我，我去邀请！我们来一期自由讨论

**Comment by LinuxSuRen** [comment]
@Otto-J 圆桌讨论是挺不错的，之后根据讨论的共识，可以再录制节目

**Comment by kang8** [comment]
> 我在第一个话题中希望可以聊聊转行程序员相关的原因就是，我就是一个转行的程序员。你是医学转行，而我是音乐学转前端开发👶

我相反，作为一个程序员，我倒是非常想组乐队玩音乐。

**Comment by wey-gu** [comment]
> > 我在第一个话题中希望可以聊聊转行程序员相关的原因就是，我就是一个转行的程序员。你是医学转行，而我是音乐学转前端开发👶
> 
> 我相反，作为一个程序员，我倒是非常想组乐队玩音乐。 @zhangchao-wooc

Me, TOO!

**Comment by shinyzhu** [comment]
话题建议：**还有专门为开发者服务的工作？/ 聊一聊开发者关系DevRel**

技术领域唯一不变的就是一直在变化，无论是开发还是设计还是运维，这些技术人都在不断学习不断刷新自己，你知道有一个专门为开发者服务的工作吗？开发者关系Developer Relation到底是什么？他们是如何帮助开发人员的？跟市场部的区别是什么？做为技术人员可以如何跟他们互动？……

希望的嘉宾：开发者布道师（Advocate），社区运营经理，DevRel PM，开发者市场经理等等……

**Comment by zhangchao-wooc** [comment]
> * 极狐手办

极狐手办😄

**Comment by amywei0811** [comment]
话题：如果未来想做技术方向创业，哪些公司以及具体的部门会是更有助益的？有什么方式可以接触创业圈子、探讨交流？

理由：从身边感受到技术工作者的施展空间越来越多元，也认识一些从side project慢慢过渡到全职做创新创业的朋友，想听听前辈们的心得教训等等

**Comment by PapayaHUANG** [comment]
播客节目：NA

话题：
1. 自学dev roadmap
2. 经典学习资源推荐（书、行业大佬、播客、视频等）
3. dev的时间精力管理分享

理由：
我从16年开始听播客，算是播客重度用户，中英文都会听。同时我也在自学准备转前端，在自学的过程中，我也想过播客这个方式，中文和英文的播客我都尝试过，但是一直没有找到内容合适的资源。
虽然我可以在youtube、书、github和技术博客收获很多知识，但是作为一个播客爱好者，还是非常希望播客也可以成为自学toolbox里面一个重要的工具。
我看了播客列表里的播客简介，再结合中文博客主要是闲聊对话的方式，以及博客的收听场景主要是通勤、做家务这种不是特别专注的时刻，所以我觉得上述三个话题在内容密度和方向上最适合我这样的群体。
关于第二个话题，我想额外提一下，我之前听过一个专门推荐播客的播客叫casticle，虽然不是技术博客，但是有一期节目介绍了havard的cs50，节目名叫[#14 开放且公平：回归新知的本质](https://www.casticle.fm/podcast-14/)，我很喜欢这期节目，也很喜欢cs50这个课程。
最后希望咱中文技术播客越办越好～

**Comment by rogerzhuuva** [comment]
大家好，感谢主办方组织的这次活动，想听到一些非计算机学历背景的程序员/创业者的职业成长故事。

p.s.我之前的工作是游戏开发，现在是互联网产品经理兼播客主播（《创意玩具》）。也欢迎大家来我的播客做客。微信/github 同ID。

**Comment by Yansufeng** [comment]
> 

极狐手办！

**Comment by Yansufeng** [comment]
> 这么多周边礼品里，有没有你期待的那一款呢？
> 
> * freeCodeCamp -  6 个背包
> * OpenTEKr - 原创拉风手袋 5 个、夜光手环一打（12 个）
> * KubeSphere - 马克杯，黑色 T恤，白色 T恤，鼠标垫各 5 个，贴纸若干干
> * 思否 - 思否猫 10 个，思否定制T恤 20 件
> * StreamNative - StreamNative周边礼盒 5 件
> * 极狐 - 极狐手办，钥匙扣各 10 件
> * Nebula Graph - 杯子，帆布袋，鼠标垫套装，T恤各五件
> * OpenMLDB - T恤 5个，鸭舌帽 5个，公仔 10个
> * ALC Beijing - 纪念币 10枚， 便签纸 10 份
> * JuiceFS - 搪瓷杯，两款，各款 6 个
> * 开源社 - 开源年会周边T恤 10 件
> * 少数派 - [麦金獭 35W 氮化镓充电器](https://sspai.com/page/retro) 2个 + [少数派会员](https://sspai.com/prime/explore) 3个
> * RTC开发者社区 - T恤 10件

极狐手办！😋

**Comment by le0zh0u** [comment]
最后统计结果~
[Yansufeng](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1158639721) 4+2+3+3+2+2 = 16 @Yansufeng 
[yuemeng200](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1158585091) 5+1+2+2+3 = 13 @yuemeng200 
[Esther-Guo](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1158658888) 3+1+1+2+2+3 = 12 @Esther-Guo 
[PapayaHUANG](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1169694170) 4+2+3 = 9 @PapayaHUANG 
[zhangchao-wooc](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1158483711) 3+1 = 4 @zhangchao-wooc 
[Kaiyiwing](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1158488475) 4 @Kaiyiwing
[DunyuSong](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1159476899) 4 @DunyuSong
[EmmyW421](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1169558632) 2+2 = 4 @EmmyW421
[shinyzhu](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1168139888) 2+1 = 3 @shinyzhu
[rogerzhuuva](https://github.com/opensource-f2f/episode/issues/118#issuecomment-1170468054) 1 @rogerzhuuva

**Comment by le0zh0u** [comment]
我们的抽奖结果已经出来了。需要参与抽奖的同学发送一下收件信息给我。
可以发送邮件 leo#leozhou.me
抽奖录屏：
https://rkawrngf0e.feishu.cn/file/boxcnm4KbGZJxMjXYmZKpAPjY6g

**Comment by LinuxSuRen** [comment]
@Yansufeng @yuemeng200 @Esther-Guo @PapayaHUANG @zhangchao-wooc @Kaiyiwing @DunyuSong @EmmyW421 @rogerzhuuva
感谢各位的参与，尽量在本月（7月份）提交个人的收件地址，考虑到会涉及到不同的礼品提供伙伴，有潜在未知的工作量。
**请一定及时提交个人信息**
超过本月的话，不能可能无法保障一定能邮寄过去。

**Comment by LinuxSuRen** [comment]
活动已结束，非常感谢各位，共建者的付出，希望每一位都有收获！！！

期待对该活动感兴趣的朋友们参与活动复盘会

https://rkawrngf0e.feishu.cn/docx/doxcnR5iwEfoF58ZSYtBZBajG7c
