### ISSUE TITLE
推荐嘉宾 - [王楠]（开源项目系列）

### ISSUE THREAD

**Issue by Nick17t** [opensource-f2f/episode#129]
### 栏目

开源岗位系列

### 嘉宾名称

王楠

### GitHub

https://github.com/nan-wang

### 公司/组织/岗位

Jina AI CTO

### 博客地址

[jina.ai/news](https://jina.ai/news/)

### 推荐理由

 Jina AI 是一家商业化开源软件公司，专注于打造针对多模态应用的 MLOps 开发运维工具。累计融资超 3700 万美金。发布了包括 [Jina](get.jina.ai)、[DocArray](https://github.com/jina-ai/docarray) 、[CLIP-as-service](https://github.com/jina-ai/clip-as-service)等多个开源项目，在 GitHub 累计收到来自全球开发者超过 35k Star的关注。作为前沿技术实践的引领者、备受市场关注的新科技公司，Jina AI 全球办公室众多岗位正在火热招聘中.....

### 推荐人

张飒

### note

- [ ] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [ ] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by LinuxSuRen** [comment]
建议的节目方向：Jina AI 公司以及开源岗位

备选话题：
* Jina AI 的由来、限制，公司文化，团队协作方式
* 主要的开源项目介绍
* 在招的开源岗位，对候选人的预期

**Comment by LinuxSuRen** [comment]
Jina AI 是公司名称。神经搜索（处理多模态数据），生成式 AI

* Jina，多模态应用的框架
* DocArray，是一个 Python 的软件包，表示、存储、传输数据

**Comment by LinuxSuRen** [comment]
参考题目：
* Jina 让所有研发轻松地借助 AI 实现很酷的想法

**Comment by acezhangjina** [comment]
参考标题：Jina AI赋能所有开发者，让超酷的多模态AI想法实现落地
