### ISSUE TITLE
推荐嘉宾 - [fydeos]（开源岗位系列）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#134]
### 栏目

开源岗位系列

### 嘉宾名称

Alpha

### GitHub

@fydeos-alpha

### 博客地址

https://www.youtube.com/channel/UCC5RcmZwxIqcPDjgArxpbOQ

### 推荐理由

[FydeOS](https://fydeos.com/content/career/) 是面向未来的操作系统，燧炻创新团队有着非常好的工程师文化，目前也有若干在招的开源相关岗位。期待和 FydeOS 的交流能给各位听友带来不一样的视角。

### 推荐人

@linuxsuren

### note

- [ ] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [ ] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by wey-gu** [comment]
Wow, cool!
Chromebook user(with an old x86 CPU that google stopped supporting it in modern versions) here, would like to try FydeOS someday ;)

Looking forward to the talk @fydeos-alpha !

**Comment by fydeos-alpha** [comment]
FydeOS 团队最近还发了自家的硬件产品，[Fydetab Duo](http://fydetabduo.cn)。很显然燧炻是一家软件公司，为什么要搞硬件，以及搞硬件怎么赚钱应该也可以聊一聊。

**Comment by LinuxSuRen** [comment]
We will record this episode at 2 pm 10/13. Please let us know if you're interested. We could send an online meeting link here.
