### ISSUE TITLE
建立飞书组织

### ISSUE THREAD

**Issue by stevending1st** [opensource-f2f/episode#152]
目前《开源面对面》很多工作基于飞书完成，却没有建立一个飞书组织，很多文档管理/查阅不便，建议建立飞书组织来协作。

**Comment by LinuxSuRen** [comment]
@stevending1st 怎么知道弄这个组织吗，你要是了解的话，可以帮忙弄一个。

**Comment by LinuxSuRen** [comment]
@stevending1st 怎么知道弄这个组织吗，你要是了解的话，可以帮忙弄一个。

**Comment by LinuxSuRen** [comment]
@stevending1st 怎么知道弄这个组织吗，你要是了解的话，可以帮忙弄一个。

**Comment by LinuxSuRen** [comment]
@stevending1st 怎么知道弄这个组织吗，你要是了解的话，可以帮忙弄一个。

**Comment by LinuxSuRen** [comment]
我已经设立好了一个飞书组织，欢迎加入

**Comment by stevending1st** [comment]
> @stevending1st 怎么知道弄这个组织吗，你要是了解的话，可以帮忙弄一个。

抱歉，我周末在 debug......

**Comment by LinuxSuRen** [comment]
> 抱歉，我周末在 debug......

没关系的。

这个 issue 先保留一周，有兴趣加入的朋友可以扫码加入。之后 issue 可以关闭了。
