### ISSUE TITLE
征集：开源面对面一周年献词（截止日期：2022 年 9 月 10 日）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#153]
2022 年 9 月 24 日将会是《开源面对面》的一周年日，特此向广大听友、嘉宾、主持人征集“一周年献词”。有意的朋友请参考以下几点：

* 内容务实、真诚，没有特意修饰
* 格式：文字或音频
* 署名：任意你喜欢的昵称（或真实姓名），或匿名
* 发布形式：文字或音频会分别拼接（剪辑）后发布
* 文字可以包括（不限于）感受、建议、期望、吐槽等
* 音频（参考问题）：如何接触到开源面对面的？对节目的寄语，对节目的建议或吐槽，其他相关内容（时长不做限，但以短小、概括为主）
* 截止日期：2022 年 9 月 10 日

> 以上只是参考，欢迎补充、调整

以下是 Rick 的献词（参考）

从 2021-09-24，思为作主持人，小马哥、Rick 录制了《开源面对面》第零期节目，之后与一些乐于讲述自己开源故事、观点的朋友们一道走来，这个以开源为主题的播客节目竟然也迎来了他（她）的一周年。想来我首先是成为了一名播客内容制作者，然后才成了播客听众，也是一件奇异的事情。但，在开源面对面的筹划、制作、传播过程中，有更多奇异、鼓舞人心的故事。

思为、Mikey 的强力加入，Logo、网站的设计，嘉宾之间互相推荐（自荐），录音棚的赞助，甚至嘉宾还会亲自动手来剪辑的惊喜。节目收到一些中肯反馈后，我们也在持续改进质量（策划、音质、剪辑、shownotes 等方面）。而让我感到尤为振奋的是：在节目嘉宾群的一次头脑风暴中，我们居然成功地发起并举办了首届“技术播客月”。18 个技术类播客之间的互动，以及媒体、平台的支持，让我更加坚定地相信开源不仅仅能存在于软件项目中，在播客制作这件事上同样行得通。

如果您认可《开源面对面》的理念，也希望通过这档节目帮助、启发更多的人，那欢迎作为嘉宾来分享您的观点；如果您感觉节目的任意方面还有待改善，欢迎提出意见或建议，甚至亲自动手来改进；如果您在开源方面有自己的思考、理念，却苦于没有适合的环境施展的话，那么这里就是值得您留意的一块试验田。

**Comment by LiMeng00** [comment]
抛砖引玉：

2022 年年初的时候，致远找到我，说他刚刚录了一期《开源面对面》的播客，问我有没有兴趣也录一期。我几乎是毫不犹豫地的就答应了，这完全是出于对致远的信任。在我参与开源之夏活动的组织过程中，致远作为 Apache APISIX 的社区代表，给了我这个一开始连开源是什么都无法准确理解的小白很多本无需提供的诸多帮助。然后就去了解节目本身，怀着诚惶诚恐的心态。

在此之前很少会去听可能与工作内容相关的播客，有限地听过的播客也是类似《看理想》这样的文艺型节目，所以声音的那一头，隔着数不尽的距离。而这一次，竟然要作为声音的发出者参与，总觉得自己是不足以有此能力的，在自己看来，发声者应当专业、有实力、有技术。但是实际的参与感却消除了这些顾虑，加入到《开源面对面》后才发现，有很多熟悉的“面孔”，慢慢地，熟悉的“面孔”越来越多，在与 Rick 的交流过程中感觉到了某种打破边界的力量感，也很开心因为自己的那一期播客，感染了身边的人。虽然没有怎么参与节目的共建，但真心为《开源面对面》越做越棒而感到高兴，可能从一开始就有一种“真诚”的情感在不断积淀吧，所以可以聚集了从大咖到小白的各路开源人一起加入进来。希望在未来，《开源面对面》也能有适当的感性内容呈现，开源是技术，但同样也是一个世界，世界的组成是无垠的。

**Comment by lijiangsheng1** [comment]
> 在开源的世界中，至关重要的一个环节就是构建对话，我以为“开源面对面”做到了，无论是更多年轻人的参与，还是保持多样性的风格。相信未来会更精彩！ 
              —— 适兕，作者，「开源之道」主创

**Comment by MikeyWei** [comment]
我听了好多年的播客（包括技术播客），也一直有做技术播客的念头，但迟迟没有行动，直到我遇见了“开源面对面”（准确地说是 Rick）。

“开源面对面”可以说是起于青萍之末，以一种我从未想象过的方式（其实是开源的方式）打开了录制技术播客的那扇门。基于谁行谁上的原则和社区理念的合作，我开始意识到原来我可以在技术播客方面做的更多，“开源面对面”用实践告诉大伙儿，与其临渊羡鱼、不如退而结网。我想这正是开源的魅力。

播客在国内也发展了许多年，但仍是一个相对小众的领域，技术播客更是小众里的小众。从多个方面来看，包括“开源面对面”在内的众多技术播客都有许多不完善的地方，期待能在“开源面对面”遇见更多对开源感兴趣的小伙伴，我们一起用开源的玩法做自己的技术播客。

**Comment by majinghe** [comment]
没有想到《开源面对面》已经走过了快一年了，还记得当初和 Rick 通过语音聊这件事，聊了一个多小时。找了思为做主持，做了第零期，开了个头，后面就有了更多人的加入。在这个过程中慢慢熟悉了播客、学习了音频剪辑。也因为《开源面对面》引出了七月份的第一届技术播客月，18 档技术播客，多人多轮多次的商讨，在没有金钱激励的情况下，大家发挥、对接了各自的资源，让技术播客月在多个平台上进行推广。

这一年有人进来了，也有人离开了，我想这就是开源 community 的魅力：有人来，有人走，但是开源面对面却还有着活力。当初完全没想到《开源面对面》会走到现在这个水平，也没想到会有这么多人参与进来。

之前说过一句话：**不美（美化）开源，不毁（诋毁）开源**，到底怎样，躬身入局感受即可。

有人来，有人走，《开源面对面》就在那里。

**Comment by DunyuSong** [comment]
最开始是从电鸭了解到《开源面对面》，没想到Rick特别热心的邀请我录制一期播客，解答了我在开源上特别多的疑惑，也让我开始了开源的第一步，后来我不仅持续的参与开源，还做了开源布道，带着身边的朋友一起玩开源。
感谢《开源面对面》，希望越办越好，让更多人了解开源、参与开源。

**Comment by wey-gu** [comment]
去年夏天，和 Rick 聊了一个多小时，到最后十几分钟才知道他想要做一个访谈节目，在那之前我都以为主题是分享 DevRel 的经验 :)。

从非常蹩脚，到尴尬程度稍微降低，我们在 podcast in public 的过程中学习如何把聊天录下来，分享出来。

参与开源面对面的初衷是希望可以像我从”捕蛇者说“、”Tea Hour“中受到的启发、陪伴那样，给面对面另一端的同学们一点点价值，这也会一直驱动我去坚持做我可以的贡献。

令我欣喜的是，作为一个日常社恐的人，在与人交流的点滴中，我总能获得额外的让我内心欢呼的美好的感触，有分享嘉宾的奇妙成长路径、鼓舞人/共鸣的开源热情、朴素的对分享/贡献的追求，也有浪漫、勇敢、又惊喜的抉择，还有几个第一次聊天的人开心成老同学聚会既视感😭

能见证、读到这些因为开源连接起来的人们，开心。

**Comment by majinghe** [comment]
> 提议：找个时间，叫齐第一期节目的几位，闲聊一下，顺便读读大家的留言。

希望疫情过去，可以回顾一下这一年。最大的感受就是真切的感受到了开源的魅力。

**Comment by miyaliu666** [comment]
我在 2021 年 11 月收到 Rick 的邀请录制一期《开源面对面》的节目，聊聊我是为什么以及如何参与到开源中的。录制前 Rick、小马哥和我的交流环节给我印象很深。当时我聊到自己目前在关注教育公益、社会创新、青年发展这三块以及一些听起来挺光鲜的经历，Rick 果断打断我，说：“我们不是想给观众呈现一个成功人士的形象，而是想挖掘你在接触、参与开源的探索过程中的各种困惑、困难，让听众感同身受，这样才能真的帮助她们”（他的原话我不记得了，大概意思就是这样）。他的一番话提醒了我去跟曾经那个在迷茫中持续探索的自己对话，甚至给节目取标题的时候，我也建议了这个标题：《S01E04-Miya 的故事｜从工地打印小妹，到全球知名教育公益开源社区大使》，当然我的重点是强调“工地打印小妹”。

Rick 和小马哥在做节目时认真挖掘故事，在平常线上、线下的交流中真诚照顾到每位参与者，这些都让我对《开源面对面》有很好的印象——他们通过点滴实际行动展示给大家“开源社区”是什么样子。

祝贺《开源面对面》满一周年，也祝我们大家在这里收获更多快乐。

**Comment by stevending1st** [comment]
作为一个两年的播客听众，在很多资深的播客听众看来无疑是“年轻”的。
在刚接触播客的时候我一直努力地寻找“计算机技术”和“开源”为主题的播客，
因为疫情原因一些开源社区的 KOL 开始录制播客，但还是很少。
现在众多开源社区开始筹备或已经有了自己的播客，这一点甚是让人欣喜。
我想说的是，随着《开源面对面》的影响力不断扩大，
将影响更多开源社区的运营者开始考虑是否要做一个播客。

如果说，一个开源社区的核心之一是要有“源码”，这一点应该会得到大多数人的同意。
但《开源面对面》作为一个不以“代码”为核心的“开放式协作组织”，
能够依赖大家“为爱发电”，良好地运行一年，已经很不容易了。
那咱就希望《开源面对面》将这件美好的事情更开放地进行下去，
如果要为这件事定一个期限，我无法像电影中的那样许下“一万年”的浪漫承诺，
至少希望，我们明年这个时候还能相见。

结识《开源面对面》是因为一次被我谢绝的录制邀请（很抱歉），但是我推荐了水歌和 S1ngS1ng 来参与，
后来也推荐了即友三咲智子，水歌的节目已经上线了，希望没有收听的朋友可以听一下。
在听节目和参与 pre talk 录制的时候，我越发觉得《开源面对面》是一档真诚质朴且打动人心的播客，
在节目中往往能和嘉宾、主持人感同身受，这一点是在现在技术播客中最为宝贵的特质。
希望新的一年，《开源面对面》感动常在。

**Comment by shinyzhu** [comment]
祝贺“开源面对面”满1周年！非常有幸能参与到这过程中。

首先要感谢 @wey-gu ，感谢siwei邀请我参与了一期个人成长的播客录制。其实我是播客很早的听众，记得春节的时候发现很多身边的人开始录制播客，当时提问是不是今年是播客年，然后就有了后面的事情。

还要感谢 @LinuxSuRen Rick。我参与到录制已经是半年后了，然后发现节目已经迭代过好几个版本和更新过好多流程了。在我参与的过程中，能感受到Rick坚持的开源协作的模式和开放的心态。所以这个节目能够很快从MVP到一个主流的播客。

还要很多要感谢的人，感谢 @PROPELLER-ZMA MINGAI 录制期间热情的介绍和总结，还有技术播客月期间的各位，当然还有群里大家热烈的讨论也给了我很多启示。

总之，是“开源面对面”节目建立了一个开放的协作平台，来自各个领域的人贡献着自己的力量。

我相信接下来的时间里，“开源面对面”会产生更多的思想碰撞和分享，为开源世界和技术世界点亮一盏明灯：）

**Comment by matrixji** [comment]
这一年通过收听《开源面对面》二十多期的节目，让我更加坚信了两件事情：参与开源有时候并不一定需要在代码上、或者软件上；内容的开源、知识的开源同样精彩。以及参与开源任何时候都不会为时过晚，需要的是只是能开始。

在此，也要非常感谢 Rick，能够邀请我参与了一期节目的录制，这让我对播客尤其是开源内容的播客有了更深入的了解，也让我对自己参与开源这件事情有了新的认识。

相信未来，《开源面对面》能够给我们带来更多新的故事和新的惊喜！

**Comment by faweizhao26** [comment]
我听播客不多，根据个人的经验和理解，勉强给节目 3 个建议，另外有一个疑问（请教）：

建议 1：建议在开头可以加个十几秒左右的 BGM（需规避版权风险），这个好处是不那么“开门见山”，方便听众“入局”；
建议 2：建议每期开头都对节目、嘉宾等进行介绍，有的新听众并不一定从第一期开始听，方便听众了解背景；
建议 3：如果是远程录制，建议提醒嘉宾注意周围环境和耳机音质（实在不行可以不用耳机），有的嘉宾音质过于差，影响听众收听。

疑问：疑问是针对建议 3 的，如何解决远程录制（线上录制）的音质问题。

**Comment by LinuxSuRen** [comment]
> 建议 1：建议在开头可以加个十几秒左右的 BGM（需规避版权风险），这个好处是不那么“开门见山”，方便听众“入局”；

这一点，我们和专业剪辑人员有请教过。简单的结论是：增加 BGM 的话需要对音乐比较敏感，所添加的音乐也要和主题相关，否则的话，容易出现适得其反的效果。简言之，这个非常考验剪辑人员的技能。在没有相对专业的人员志愿加入的话， BGM 可能不太容易处理。

至于版权问题，这一点比较好处理。已经有一些网站专门提供 Free License 的音乐可用，可以在哔哩哔哩、小宇宙、喜马拉雅等平台获取。

> 建议 2：建议每期开头都对节目、嘉宾等进行介绍，有的新听众并不一定从第一期开始听，方便听众了解背景；

这个建议相对比较容易实现，也确实有助于品牌的树立。

> 建议 3：如果是远程录制，建议提醒嘉宾注意周围环境和耳机音质（实在不行可以不用耳机），有的嘉宾音质过于差，影响听众收听。

对于这一点，在我们的每个嘉宾 issue 中都给出了一个链接，里面介绍了如何处理远程录制的问题。例如 https://github.com/opensource-f2f/episode/issues/159

最后再次表示对 @faweizhao26 提出的建议而表示感谢！

**Comment by LinuxSuRen** [comment]
感谢每一位关注过《开源面对面》的朋友们，既然我们声称这档节目是以开源的形式在布道开源，节目的一些数据作为比较重要的信息，作为公示在此一周年也分享给可能对此感兴趣的朋友们。当然，此外任何人在任何时候都可以拿到数据。

![image](https://user-images.githubusercontent.com/1450685/191390329-76020145-ccc7-4d0b-9cc9-47e9e77c7987.png)
![image](https://user-images.githubusercontent.com/1450685/191390663-f795cbcf-9bfc-40c1-b754-4ff1eb1d3bb2.png)
![image](https://user-images.githubusercontent.com/1450685/191390736-1c9e2f62-d3c8-46ec-b341-ce9bdc6f876e.png)
![image](https://user-images.githubusercontent.com/1450685/191390790-8197a44f-2350-4e29-9385-fdf8aab34961.png)
![image](https://user-images.githubusercontent.com/1450685/191390828-40d428bc-f651-4a3a-9d98-c351f5acaf00.png)
![image](https://user-images.githubusercontent.com/1450685/191390380-7dfd622e-c081-496c-8397-d708d7fc0ff5.png)
![image](https://user-images.githubusercontent.com/1450685/191390403-c930047a-e887-47f2-96c2-12ebbd7eabfa.png)
![image](https://user-images.githubusercontent.com/1450685/191390424-08ef00ce-dbe2-4259-83c3-3924bc4f6804.png)
![image](https://user-images.githubusercontent.com/1450685/191390575-a2c9b8e6-7d36-4779-8bde-438970c5009f.png)
