### ISSUE TITLE
Distribute to Spotify/ Google Podcast

### ISSUE THREAD

**Issue by wey-gu** [opensource-f2f/episode#18]
As titled.

context: https://twitter.com/super_leeyom/status/1473143175527088131?s=20 by @superleeyom

**Comment by wey-gu** [comment]
cc @LinuxSuRen

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/146879249-9bf7c6f1-0345-4dcd-aa86-3a173b11c29d.png)

有同学知道该怎么操作吗？

**Comment by LinuxSuRen** [comment]
Google 上面大家能搜索到吗 
![image](https://user-images.githubusercontent.com/1450685/146879344-c342450d-8140-4507-bd98-979efc49540c.png)

**Comment by wey-gu** [comment]
> ![image](https://user-images.githubusercontent.com/1450685/146879249-9bf7c6f1-0345-4dcd-aa86-3a173b11c29d.png)
> 
> 有同学知道该怎么操作吗？

I am using Spotify actually(ref bottom of https://github.com/wey-gu ), will assign myself and look into it.

**Comment by superleeyom** [comment]
> ![image](https://user-images.githubusercontent.com/1450685/146879249-9bf7c6f1-0345-4dcd-aa86-3a173b11c29d.png)
> 
> 有同学知道该怎么操作吗？

把代理节点切到台湾或者新加坡试试？

**Comment by wey-gu** [comment]
@LinuxSuRen it turned out Spotify requires RSS to include `iTunes:email` field, could you look into the ximalaya RSS output format to see how to add that field?

```xml
<itunes:owner>
    <itunes:email> youremailaddress@gmail.com </itunes:email>
</itunes:owner>
```

**Comment by LinuxSuRen** [comment]
Sorry about that. But I didn't find any places where we can add it.

**Comment by LinuxSuRen** [comment]
> 把代理节点切到台湾或者新加坡试试？

我的这个没用切换功能。。。。尴尬

**Comment by wey-gu** [comment]
It turned out ximalaya doesn't provide options to add this field :(.
https://anchor.fm/ can provide this, while it required another distribution platform.

**Comment by wey-gu** [comment]
Maybe it's easier to parse the rss XML in like github actions and serve the one with ` <itunes:email> ` added, and then submit it to Spotify.

**Comment by LinuxSuRen** [comment]
> Maybe it's easier to parse the rss XML in like github actions and serve the one with `<itunes:email>` added, and then submit it to Spotify.

This might be a good solution. We can re-render the RSS XML content.

**Comment by wey-gu** [comment]
I will do it when I have bandwidth to.

**Comment by wey-gu** [comment]
本来在写脚本填坑，然后发现 xml 里边已经有这个字段了，现在提交成功了✿✿ヽ(°▽°)ノ✿

https://open.spotify.com/show/48Yeu1L5pTluk1AVc3ShU6

cc @superleeyom

**Comment by superleeyom** [comment]
cool🥳 @wey-gu
