### ISSUE TITLE
推荐嘉宾 - [程旭文/程开源]（个人成长系列）

### ISSUE THREAD

**Issue by MikeyWei** [opensource-f2f/episode#183]
### 栏目

个人成长

### 嘉宾名称

程旭文/程开源

### GitHub

https://github.com/fat1

### 公司/组织/岗位

环信联创VP

### 博客地址

微博 https://weibo.com/iamstevencheng

### 推荐理由

[@程开源](https://github.com/fat1)本名程旭文，从2001左右开始接触开源（最早接触的是ACE和TAO），曾参与国内较早的开源社区[灰狐](https://www.huihoo.com/)（主理人龙辉）并创办[息壤开源社区](www.sarons.org)（此息壤非彼 ~~开源工场和中科大LUG联合发起~~ 的[息壤](https://hexang.org)），现任[环信](https://www.easemob.com/)联创 VP。

在十年前的一篇采访《[“我们的开源项目”发起人、息壤开源社区共同创始人——程旭文专访](https://blog.csdn.net/blogdevteam/article/details/7889760)》中他提到一些观点：

- 发起成立息壤开源社区是尝试在中国建立一个类似于Apache基金会一样的组织，尝试解决开源协作过程中的规则问题。
- 需要特别说明的，很多人包括做过多年开源的人，都不太分得清开源License与CLA的区别，开源License我们见得比较多，如GPL、LGPL、MIT等，开源License实际是发布和授权协议，针对的对象是开源的使用者和传播者，建立开源在传播和使用中的规则；而CLA是针对开源的生产者，约束开发者间的协作关系。
- 对国内开源环境的看法是随着云计算的普及，开源的玩法会更丰富。
- 建议致力于参与开源的开发者，秉持“just for fun”的心态。

可以从“如何在企业中持续参与开源、国内企业开源的现状与发展”为题，请这位开源老兵谈谈自己的心得体会。

### 推荐人

@MikeyWei

### note

- [ ] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [ ] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by LinuxSuRen** [comment]
赞，欢迎加入 [Slack](https://join.slack.com/t/osf2f/shared_invite/zt-1j99x39t2-IYUsfBgTmXCfni5iNq5TXg) 或微信群交流
