### ISSUE TITLE
提议：禅道为节目提供周边礼品

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#204]
按照年度，例如：23年

禅道提供 2023 年的礼品赞助

方式：
* 每一位嘉宾、主持人提供一份，不重复计数
* 给听友礼品（不好操作）
* 独家
* 由于节目没有经费，需要禅道帮忙邮寄
* （可选）把双方的 Logo 或者名称放在一起

**Comment by stevending1st** [comment]
这是对方提议，还是？

我理解以下两条是赞助：

> * 每一位嘉宾、主持人提供一份，不重复计数
> * 给听友礼品（不好操作）

以下是条件：

> * 独家
> * 由于节目没有经费，需要禅道帮忙邮寄
> * （可选）把双方的 Logo 或者名称放在一起

？？？

**Comment by LinuxSuRen** [comment]
抱歉，还没来得及解释。上面是和禅道的同学讨论的一些记录。具体请参考下面的会议录屏

https://www.bilibili.com/video/BV1zM411e7T5/?vd_source=ca1041974e9b44975cc4d5355ad7001f

**Comment by stevending1st** [comment]
还有海外参与者，邮寄问题应该向其说明。

**Comment by LinuxSuRen** [comment]
> 还有海外参与者，邮寄问题应该向其说明。

是的。这需要补充好这一点。

**Comment by majinghe** [comment]
我没记错的话，已经通过公众号发布了，[开源面对面 & 禅道，惊喜掉落](https://mp.weixin.qq.com/s/K9zhFsbhd2cwHNnTzV-ehg)。


@LinuxSuRen 这个 issue 是不是可以关闭了。
