### ISSUE TITLE
将播客托管平台迁移到声湃并更新 RSS 订阅地址为官网域名

### ISSUE THREAD

**Issue by MikeyWei** [opensource-f2f/episode#205]
在各位小伙伴的努力下，我们搭建了官网，录了几期节目，并对播客的制作全流程有了更深入的了解。

秉承开源的精神，我提议播客的分发环节可以更开放些，通过一些调研和交流，发现[声湃](https://wav.pub/)在现阶段和规划中比较契合这个思路。目前声湃正在规划整合统一登录方面的功能，在可期的时间内，有望实现主播们通过 GitHub 账号无缝参与节目的制作和发布。

在声湃小伙伴的帮助下，我们先完成现有播客节目的迁移和跨平台的推送（尤其是 osf2f 域名订阅链接的重要性），也欢迎有前端能力和意愿的小伙伴一起参与后续功能的实现。

**Comment by stevending1st** [comment]
> 在声湃小伙伴的帮助下，我们先完成现有播客节目的迁移和跨平台的推送（尤其是 osf2f 域名订阅链接的重要性），也欢迎有前端能力和意愿的小伙伴一起参与后续功能的实现。

需要做什么吗？

**Comment by LinuxSuRen** [comment]
已经邀请 @zhufengme 加入 @tech-podcasts，@zhufengme 会把他的一些音频处理代码开源

![image](https://user-images.githubusercontent.com/1450685/221451705-c62ccc5a-3bb3-4ebf-b6f2-98e8df6cfdbd.png)
