### ISSUE TITLE
推荐嘉宾 - [王嘉树]（个人成长系列）

### ISSUE THREAD

**Issue by LiMeng00** [opensource-f2f/episode#212]
### 栏目

个人成长系列-学生篇

### 嘉宾名称

王嘉树

### GitHub

https://github.com/wjsvec/

### 推荐理由（着重考虑开源爱好者能收获什么）

王嘉树，北京邮电大学研二在读，曾参与开源之夏 [TDengine visual studio code](https://github.com/taosdata/vscode-tdengine) 项目并顺利结题，活跃在 TDengine 社区。目前的兴趣在开源项目方面，曾在科大讯飞、电信研究院等实习。

作为开源之夏学生群体中活跃的典型代表，展现出了突出的组织能力和实践能力，体现了开源在学生群体中日益高涨的活力。

### 推荐人

李梦 @LiMeng00 

### note

- [X] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [X] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by LinuxSuRen** [comment]
已经发送邀请加入 org
![image](https://user-images.githubusercontent.com/1450685/229421672-4d157bc0-740b-4506-8b1b-ab7959eb86ae.png)

**Comment by LinuxSuRen** [comment]
Here is the pre-talk link https://meeting.tencent.com/dm/sC4cjaOcGhid

**Comment by wey-gu** [comment]
cool!

**Comment by LinuxSuRen** [comment]
By the way, the meeting time is 10 am at 4/9.

**Comment by LinuxSuRen** [comment]
The document link at here https://docs.qq.com/doc/DYUhBVEJrRVZpVEZT

**Comment by wjsvec** [comment]
## Twitter
[No response](https://twitter.com/0kKL7jN4t57kiR6)

## 博客地址
wjsvec.github.io
blog.csdn.net/wjsvec
