### ISSUE TITLE
推荐嘉宾 - [张跃骎]（个人成长系列）

### ISSUE THREAD

**Issue by wu-sheng** [opensource-f2f/episode#213]
### 栏目

个人成长系列

### 嘉宾名称

张跃骎

### GitHub

https://github.com/yswdqz

### 推荐理由（着重考虑开源爱好者能收获什么）

张跃骎落选了2022年SkyWalking的开源项目，@Superskyyy 组织了针对落选学生的自发学习小组。张跃骎在活动中联系到我，在近10个月的时间中，利用自身时间参与了SkyWalking大量功能贡献。成为SkyWalking Committer。

### 推荐人

吴晟

### note

- [ ] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [ ] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by LinuxSuRen** [comment]
感谢 @wu-sheng 邀请嘉宾。

已经邀请 @yswdqz 加入 org

![image](https://user-images.githubusercontent.com/1450685/231113055-c52c7a02-841f-470b-aec3-c89eb16a82b0.png)

**Comment by LinuxSuRen** [comment]
@yswdqz 您抽空加一下我微信，我们有个嘉宾微信群（无广告）

**Comment by LinuxSuRen** [comment]
> 好的，我应该怎么加您微信 ?

抱歉，忘记了。微信同 GitHub ID

**Comment by shinyzhu** [comment]
欢迎。
欢迎 SkyWalking Contributor~

**Comment by LinuxSuRen** [comment]
hi @yswdqz , the pre-talk link is https://meeting.tencent.com/dm/3h87fAfRLEz9

**Comment by wjsvec** [comment]
Here is the pre-talk link: https://meeting.tencent.com/dm/qiOdKW9RPASt

The document link at here: https://docs.qq.com/doc/DQ3ZGVG52eGllWGlO

😊

**Comment by LinuxSuRen** [comment]
So glad to have @wjsvec to push this episode forward.

**Comment by LinuxSuRen** [comment]
The official record meeting link https://meeting.tencent.com/dm/AUhIkOmpOmuK

**Comment by yswdqz** [comment]
committer weicome：
https://skywalking.apache.org/events/welcome-yueqin-zhang-as-new-committer/

评论比较多，主要是讨论的PR
https://github.com/apache/skywalking/pull/9575

评论比较多，主要是我早期比较愚蠢的问题的PR
https://github.com/apache/skywalking/pull/9432

**Comment by wjsvec** [comment]
跃骎同学今年参加的开源之夏项目：
https://summer-ospp.ac.cn/org/prodetail/237cc0232?list=org&navpage=org

吴晟老师关于开源之夏申请的一些讨论：
https://twitter.com/wusheng1108/status/1651111988251197443

**Comment by wjsvec** [comment]
剪辑新手，有一些对话处理的可能不太好🥲。Rick 的噪音有些严重做了简单的降噪，我和跃骎的还好就保持原状了


https://nioioen9tb.feishu.cn/file/KfqNb9wv2oQB7WxJJbGc4JV6n8e?from=from_copylink

**Comment by LinuxSuRen** [comment]
我发现从第24秒才开始有声音，帮忙确认下是否有这个问题。

我的麦克风应该是有问题，后续多多注意。

**Comment by wjsvec** [comment]
> 

啊失误失误，空白的音轨忘记删除掉了🥲，在 audacity 里面一直没有听出来。

**Comment by LinuxSuRen** [comment]
> 啊失误失误，空白的音轨忘记删除掉了🥲，在 audacity 里面一直没有听出来。

我来处理前面的空白，以及 shownotes 吧。

**Comment by LinuxSuRen** [comment]
本期标题：S01E21 张跃骎：落选后竟然成为 SkyWalking Committer

**Comment by LinuxSuRen** [comment]
音频调整后的链接 https://rkawrngf0e.feishu.cn/file/EIntb5HdfonxOzxYDXEc4mYjnef?from=from_copylink

**Comment by wu-sheng** [comment]
今天完整了听了一下，音轨似乎对齐有点问题，其中时不时出现两个人都在说话，然后感觉有明显的留白。建议再调整一下时间线，会对听众更友好一些。

**Comment by LinuxSuRen** [comment]
@wu-sheng 感谢反馈，我们重新剪辑一下，预计本周末可以出一个版本。
