### ISSUE TITLE
使用 twitter 账号申请

### ISSUE THREAD

**Issue by wjsvec** [opensource-f2f/episode#228]
我希望可以在社交媒体上运营一下，可以更好的与听友互动或是收集一些意见

**Comment by LinuxSuRen** [comment]
@wjsvec 在 Twitter 上很活跃，而且，参与过节目录制两期（其中一期还在剪辑中）。欢迎并感谢 @wjsvec 帮忙打理 Twitter 账号！！！
已经邀请加入 admin team

**Comment by wey-gu** [comment]
✿✿ヽ(°▽°)ノ✿
欢迎 @wjsvec !
