### ISSUE TITLE
【CommunityOverCode Asia 宣传】会出席 Apache Con 的开源面对面嘉宾

### ISSUE THREAD

**Issue by wjsvec** [opensource-f2f/episode#231]
预期写成一篇微信公众号推送，不知道是不是有所遗漏。如果可以的话请帮忙补充一下子

节目嘉宾王殿进：
    参与节目：[https://osf2f.net/episode/S02E02](https://osf2f.net/episode/S02E02)
    CommunityOverCode Asia ：消息系统会场出品人

节目嘉宾 tison：
    参与节目： [tison：一名 Community Builder 的自白](https://osf2f.net/episode/S01E17 )
     CommunityOverCode Asia： 开源社区会场出品人

节目主持人 Rick：
    参与节目：差不多全部
     CommunityOverCode Asia： 2023-08-19 14:30 - 15:00 面对开源，你还只有用“爱”发电吗？

节目嘉宾王嘉树：
    参与节目：[开源之夏学生专访-王嘉树](https://osf2f.net/episode/S01E20)
     CommunityOverCode Asia：2023-08-19  15:45 - 16:15   开源之夏最佳实践

其它：Keynote 主题演讲出品人姜宁和节目主持人 Rick 在的 alc beijing 的播客：[No. 25：Talk_Is_Not_Cheap！](https://www.xiaoyuzhoufm.com/episode/6363a6bdea3c62a2129dd9f5
)

**Comment by LinuxSuRen** [comment]
还有以下：

节目嘉宾：李梦
参与节目：[面对开放的大门，技术小白可以怎样开始参与开源](https://osf2f.net/episode/S01E07)
