### ISSUE TITLE
推荐嘉宾 - [林旅强 Richard]（个人成长系列）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#232]
### 栏目

个人成长系列

### 嘉宾名称

林旅强 Richard

### GitHub

[legist](https://github.com/legist)

### Twitter

[richardllin](https://twitter.com/richardllin)

### 推荐理由（着重考虑开源爱好者能收获什么）

Richard 林旅强，在开源之夏、开源社等相关的活动中都有不少的参与。其朴实、深刻的开源认识、观点对 @LinuxSuRen 了解、参与开源有着很深的影响。@LinuxSuRen 特别希望他对开源的热情可以传递给《开源面对面》的朋友们。

### 推荐人

@linuxsuren

### note

- [ ] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [ ] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by LinuxSuRen** [comment]
相关分享

【开源之夏2023专家寄语——Richard 林旅强】 https://www.bilibili.com/video/BV1u8411S7G7/?share_source=copy_web&vd_source=1e8d9e70686a4845fa44f8d3f5ff7925

【暑期2020“大咖说开源”| 庄表伟、林旅强：说说你人生经历中的开源故事】 https://www.bilibili.com/video/BV1Ni4y1x7LY/?share_source=copy_web&vd_source=1e8d9e70686a4845fa44f8d3f5ff7925

【【开源社】开源小故事 庄表伟&林旅强】 https://www.bilibili.com/video/BV1Sg4y1v7EX/?share_source=copy_web&vd_source=1e8d9e70686a4845fa44f8d3f5ff7925

【OpenTEKr｜大话开源精华版｜林旅强：开源之于创新 有时无招胜有招】 https://www.bilibili.com/video/BV1bf4y1g7qp/?share_source=copy_web&vd_source=1e8d9e70686a4845fa44f8d3f5ff7925

**Comment by shinyzhu** [comment]
欢迎强哥！录的时候我要来参加：）

**Comment by LinuxSuRen** [comment]
暂定本周六（Apache Con）下午三点录制，以下是参考话题

【腾讯文档】开源面对面&Richard
https://docs.qq.com/doc/DYWxuSWtjQlpCTXpn

**Comment by LinuxSuRen** [comment]
@shinyzhu 有预计大概什么时候会剪辑出来吗？另外，在发布之前，需要找相关人确认下。感谢提供后期支持！

**Comment by shinyzhu** [comment]
> 

大概这周末（27号前）完成，剪辑完成我先更新到各位确认：）

**Comment by shinyzhu** [comment]
@LinuxSuRen @legist @MikeyWei @wjsvec 
剪辑基本完成。
文档：https://w703h2pk3f.feishu.cn/docx/IbglduwrJo1nsgxV1RScL0Uqnhf?from=from_copylink
音频：https://w703h2pk3f.feishu.cn/file/SuRSbszKzoFkGvxnw8ycqpZ9n1e

**Comment by wey-gu** [comment]
> @LinuxSuRen @legist @MikeyWei @wjsvec 剪辑基本完成。 文档：https://w703h2pk3f.feishu.cn/docx/IbglduwrJo1nsgxV1RScL0Uqnhf?from=from_copylink 音频：https://w703h2pk3f.feishu.cn/file/SuRSbszKzoFkGvxnw8ycqpZ9n1e

👍！

**Comment by LinuxSuRen** [comment]
片尾音乐非常赞！到时候可以在 shownote 中把使用的工具以及片尾英语都做一下说明。
我 review 过了，部分我的声音听起来比较低（例如：45:02 处）以外，整体都非常好。

**Comment by shinyzhu** [comment]
> 片尾音乐非常赞！到时候可以在 shownote 中把使用的工具以及片尾英语都做一下说明。 我 review 过了，部分我的声音听起来比较低（例如：45:02 处）以外，整体都非常好。

抱歉。有几个时间点音轨没有切换。修复版本音频文件在这里：https://w703h2pk3f.feishu.cn/file/OT8dbiFMtoU0fvxyIaQcMItDnJc?from=from_copylink

**Comment by shinyzhu** [comment]
> 片尾音乐非常赞！到时候可以在 shownote 中把使用的工具以及片尾英语都做一下说明。 我 review 过了，部分我的声音听起来比较低（例如：45:02 处）以外，整体都非常好。

抱歉。有几个时间点音轨没有切换。修复版本音频文件在这里：https://w703h2pk3f.feishu.cn/file/OT8dbiFMtoU0fvxyIaQcMItDnJc?from=from_copylink

**Comment by shinyzhu** [comment]
> 片尾音乐非常赞！到时候可以在 shownote 中把使用的工具以及片尾英语都做一下说明。 我 review 过了，部分我的声音听起来比较低（例如：45:02 处）以外，整体都非常好。

抱歉。有几个时间点音轨没有切换。修复版本音频文件在这里：https://w703h2pk3f.feishu.cn/file/OT8dbiFMtoU0fvxyIaQcMItDnJc?from=from_copylink

**Comment by LinuxSuRen** [comment]
对应的 Twitter 链接

https://twitter.com/osf2f/status/1689166651772878848
