### ISSUE TITLE
推荐嘉宾 - 吴晟（开源项目系列）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#237]
### 栏目

开源项目系列

### 嘉宾名称

吴晟

### GitHub

@wu-sheng

### Twitter

[wusheng1108](https://twitter.com/wusheng1108)

### 推荐理由（着重考虑开源爱好者能收获什么）

吴晟是 [Apache](https://github.com/apache) [成员](https://apache.org/foundation/members)以及首位华人董事，[Apache SkyWalking](https://github.com/apache/skywalking) 项目创始人。

他同时也是 [incubator](http://people.apache.org/phonebook.html?pmc=incubator) PMC 成员，希望可以通过对他的采访能让大家对项目进入 Apache 孵化的流程更加了解，包括但不限于：

* 什么样的项目（类型、阶段）适合进入 Apache 孵化
* Apache Incubator 能帮助项目解决哪些问题，不能解决哪些
* 一些正反面案例分享

采访尽量从对 Apache 不是很熟悉的角度来进行，帮助大家对 Apache 旗下项目有更清晰、准确的认识。

欢迎对此话题感兴趣的朋友们在 issue 下面留言，我们会考虑把问题纳入节目录制中。

### 推荐人

@linuxsuren

### note

- [ ] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [ ] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by tk103331** [comment]
请问能不能介绍下导师在孵化期间发挥的作用

**Comment by wjsvec** [comment]
一个国际化的项目应该要有完善的英文文档。除了英文文档，一个国际化的项目还应该做好哪些事情呢

**Comment by wey-gu** [comment]
期待🤩

**Comment by chaunceyjiang** [comment]
进入 Apache 孵化 有什么硬性条件吗？ 比如 Star 数？ 社区用户数？ 外部贡献者数量？

**Comment by sunheyi6** [comment]
如何确认这个项目存在的真正意义

**Comment by shinyzhu** [comment]
十分期待。

我也可以预约个后期吧：）

**Comment by joostshao** [comment]
podcast 或者 youtube ， 加油！

**Comment by LinuxSuRen** [comment]
> podcast 或者 youtube ， 加油！

按照常规的话，会播客的形式，可以在小宇宙或者 Podcat 上收听，感谢关注和支持！

**Comment by QuakeWang** [comment]
期待！！

**Comment by LinuxSuRen** [comment]
Twitter 已经 follow，也邀请加入当前 GitHub Org

![image](https://github.com/opensource-f2f/episode/assets/1450685/ea705251-e27a-4c40-b555-51e629844fa0)
![image](https://github.com/opensource-f2f/episode/assets/1450685/c0d0c900-ed41-4568-b7d8-3c09d590a252)

**Comment by LinuxSuRen** [comment]
我整理了一份参考议题清单，欢迎大家补充完善。

https://docs.qq.com/doc/DYUlVYXJrRFNLdlpE

**Comment by sunheyi6** [comment]
> 我整理了一份参考议题清单，欢迎大家补充完善。
> 
> https://docs.qq.com/doc/DYUlVYXJrRFNLdlpE

登录之后还需要申请权限才行，感觉不方便查看

**Comment by LinuxSuRen** [comment]
@sunheyi6 感谢提醒，已经开通所有人可见了，要修改的话，还是需要申请下。

**Comment by Young-Flash** [comment]
ASF 的资金从哪里来？花到哪里去？孵化器的项目如果不能毕业会怎么样？

**Comment by LinuxSuRen** [comment]
> ASF 的资金从哪里来？花到哪里去？孵化器的项目如果不能毕业会怎么样？

感谢回复，有关 ASF 的话题会有很多，这次会聚焦到孵化器相关。您反馈的前两个问题，我会记录到文档中，但可能不能展开讲。

**Comment by LiMeng00** [comment]
为什么这么多项目想要借孵化器的“东风？

**Comment by node** [comment]
提问： 
新项目申请进入 Incubator 每个基金会一般都有明确的标准，从预期和经验角度来说项目在申请前会进行自检，持续接近该标准。 但实际上，任何人都可以随便提交申请，只是会收到一个拒绝而已。

那么，对于有计划申请进入  Incubator 的早期项目来说，如何更好地自我检查和完善，以尽可能接近 Incubator 的标准？

**Comment by LinuxSuRen** [comment]
@node Good question.

**Comment by wu-sheng** [comment]
> 提问： 新项目申请进入 Incubator 每个基金会一般都有明确的标准，从预期和经验角度来说项目在申请前会进行自检，持续接近该标准。 但实际上，任何人都可以随便提交申请，只是会收到一个拒绝而已。
> 
> 那么，对于有计划申请进入 Incubator 的早期项目来说，如何更好地自我检查和完善，以尽可能接近 Incubator 的标准？

这是个好问题， 实际上这次的OzHera和这里描述的项目随意提交，不是一个性质的问题。以为OzHera的Proposal发送来自IPMC成员，且已经有数名其他IPMC成员的署名了。我们可以在博客中，进一步聊聊这个问题。

**Comment by majinghe** [comment]
一直有一个问题，之前也跟 @LinuxSuRen 交流过，要跟吴晟老师聊的话，就想问一下：SkyWalking 这个项目是 Apache 顶级项目，在 APM 领域也是很优秀的，这样一个项目，估计之前也有很多 VC 追着投资，想让吴晟老师创业，但是吴晟老师似乎并没有走这条路，其实比较好奇这一点。

PS：在开源热的前几年，大厂内部孵化的项目，项目组成员出来创业，拿到 VC 钱的也不在少数。感觉 SkyWalking 很特别。

**Comment by LinuxSuRen** [comment]
@majinghe 我感觉可以把这个作为单独的一期来分享一下。

**Comment by wu-sheng** [comment]
> 一直有一个问题，之前也跟 @LinuxSuRen 交流过，要跟吴晟老师聊的话，就想问一下：SkyWalking 这个项目是 Apache 顶级项目，在 APM 领域也是很优秀的，这样一个项目，估计之前也有很多 VC 追着投资，想让吴晟老师创业，但是吴晟老师似乎并没有走这条路，其实比较好奇这一点。
> 
> PS：在开源热的前几年，大厂内部孵化的项目，项目组成员出来创业，拿到 VC 钱的也不在少数。感觉 SkyWalking 很特别。

创业就很见仁见智了 ：） 看大家是不是觉得这是个有共性的话题了

**Comment by He-Pin** [comment]
捐献给Apache 的项目，商标什么的都是Apache 的了吧。IP 和原来的捐献者还有什么关系吗？Apache 的项目知识产权和商用许可是怎么样的呢。

**Comment by shinyzhu** [comment]
剪辑已完成，导出的文件地址：https://w703h2pk3f.feishu.cn/file/NOrnbWrlro0mpoxEcUwcsUNQnIg?from=from_copylink

欢迎 @MikeyWei @LinuxSuRen 试听和反馈。

```
Show Notes
00:00:00 嘉宾介绍
00:03:06 快闪问答，一次搞懂8个问题消除误解
00:05:05 Apache 孵化器的人员构成及项目策略详解
00:45:55 听友提问详细回答
01:21:55 Community Over Code 背后原因和解读
01:26:17 结束语和感谢
```

**Comment by wu-sheng** [comment]
> 调音非常棒，辛苦 @shinyzhu 的付出。建议修改部分为：34‘10’‘~34’20‘’ 处，

这个地方确实有一点点，看看是不是需要修复。个人感觉也能接受。

**Comment by shinyzhu** [comment]
新版本已上传，地址同上。确认选择新版本文件即可：）

**Comment by LinuxSuRen** [comment]
感谢 @shinyzhu

**Comment by wu-sheng** [comment]
S04E00-吴晟：开源项目进入 Apache 孵化器意味着什么

https://www.xiaoyuzhoufm.com/episode/651fb7082e5a4700d96ccc71
