### ISSUE TITLE
嘉宾推荐 - 李梦

### ISSUE THREAD

**Issue by juzhiyuan** [opensource-f2f/episode#24]
所在单位：中科南京软件技术研究院
单位网站：http://nj.iscas.ac.cn/
工作职责：开源之夏活动负责人之一
推荐理由：自 2020 年首届开源之夏活动起，李梦老师便活跃在国内各个开源项目组织、各个高校学生群中，鼓励大家参与、分享、提升。希望从活动组委会负责人的视角，分享她对国内开源项目、社区以及高校学生参与等方面，分享自己的心得与想法。
活动网站：https://summer.iscas.ac.cn/
推荐人：[琚致远](https://github.com/juzhiyuan)

**Comment by LinuxSuRen** [comment]
开源之夏是非常有意义的一个活动，非常期待。不知道是否有李梦的GitHub账号呢，我们通常会把嘉宾邀请到这个org中

@juzhiyuan 方便帮忙联系下李梦，如果她（他）愿意的话，可以拉到我们的微信群中。

**Comment by LiMeng00** [comment]
Hi 老师们好，很荣幸受邀，希望开源之夏能与更多的朋友结缘。

**Comment by LinuxSuRen** [comment]
@LiMeng00 欢迎，已发 GitHuh team 邀请

**Comment by LinuxSuRen** [comment]
正式录制的会议链接：https://meeting.tencent.com/dm/1GZx7nmCWbuO

**Comment by LinuxSuRen** [comment]
录制的内容已经上传飞书
https://rkawrngf0e.feishu.cn/docs/doccnyerrkGdopqQoxKdy1k6yhf#

**Comment by kang8** [comment]
close #71

**Comment by LinuxSuRen** [comment]
README 里还没有添加对应记录呢
