### ISSUE TITLE
制作易拉宝，用来在中国开源年会现场摆放

### ISSUE THREAD

**Issue by majinghe** [opensource-f2f/episode#254]
第八届中国开源年会 10.28-10.29 将在成都举行。有一个开源茶馆区域可以摆放易拉宝，因此打算设计制作一个易拉宝，邮寄到成都，在中国开源年会现场使用。

由于开源面对面目前没有设计师，因此易拉宝需要 vendor 设计，当前聊下来的费用为：

* 易拉宝打印费用：120元（标准易拉宝）
* 设计费：80元
* 邮寄费（顺丰特快，确保周六能到或者最好周五到）：23元 左右

总计 223元。

**Comment by majinghe** [comment]
目前计划，易拉宝上面的内容为：

* 开源面对面介绍，取自 GitHub 首页介绍

```
《开源面对面》是一个系列的访谈节目，旨在通过采访不同行业、岗位的开源参与者的亲身经历、心得体会，让更多的从业人员看到参与开源是一种积极的趋势与良好的职业发展方向，认识到任何人都可以参与开源，并在开源的世界里体现自己的价值。
```

* 官网首页截图展示

![Screen Shot 2023-10-25 at 10 51 51 AM](https://github.com/opensource-f2f/episode/assets/42570491/7534f054-9399-465e-8c35-2b5faf9ade81)

* 其他展示内容

    - 官网地址
    - GitHub 地址
    - 公众号二维码
    - 小宇宙二维码

@LinuxSuRen 看看可以不。

**Comment by LinuxSuRen** [comment]
网站截图看怎么能更好的呈现在易拉宝上。

感谢 @majinghe 帮忙张罗，这将会是我们的第一个易拉宝！！！

**Comment by majinghe** [comment]
> 网站截图看怎么能更好的呈现在易拉宝上。

这个就看设计师的了。这些内容可以重新整合。

**Comment by stevending1st** [comment]
我刚刚问了 COSCon 的供应商，价格相对便宜。

80*180的是54 易拉宝

120*200的是108 门型展架

**Comment by majinghe** [comment]
> 我刚刚问了 COSCon 的供应商，价格相对便宜。
> 
> 80*180的是54 易拉宝
> 
> 120*200的是108 门型展架

拿这个合适，我感觉80*180 的就行，不用门型的。简易的就行。那设计费呢。我们没有设计师，还的让那边帮忙设计一下。

**Comment by stevending1st** [comment]
> > 我刚刚问了 COSCon 的供应商，价格相对便宜。
> > 
> > 80*180的是54 易拉宝
> > 
> > 120*200的是108 门型展架
> 
> 拿这个合适，我感觉80*180 的就行，不用门型的。简易的就行。那设计费呢。我们没有设计师，还的让那边帮忙设计一下。

可以免费设计

**Comment by wey-gu** [comment]
我来 sponsor 费用吧

**Comment by LinuxSuRen** [comment]
我也来 Sponsor 一部分

**Comment by majinghe** [comment]
高效地完成了易拉宝的设计，虽然看起来不太美观，但是这是开源面对面的第一个易拉宝，要摆放到中国开源年会现场。设计定稿为：

![WechatIMG111](https://github.com/opensource-f2f/episode/assets/42570491/8a951db8-2900-47aa-ae03-724c2bcc2267)

到时候在现场拍些照片再贴出来。

**Comment by LinuxSuRen** [comment]
感谢 @wey-gu @majinghe @stevending1st @wjsvec 等同学的共同协作，最终费用为 67 元。此次易拉宝由 @wey-gu @majinghe @LinuxSuRen 共同赞助，在爱发电上结余的 28.2 元由 @LinuxSuRen 代为管理。

**Comment by LinuxSuRen** [comment]
特别懂牙的痛。

**Comment by LinuxSuRen** [comment]
美照上线
![image](https://github.com/opensource-f2f/episode/assets/1450685/420f8690-38dc-443c-a255-5e9f7000a9c4)
