### ISSUE TITLE
RSS 无法添加到豆瓣平台

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#263]
![image](https://github.com/opensource-f2f/episode/assets/1450685/61f55d48-36b2-4585-9361-d1fe42d93e3e)

如上图所示，我们节目当前无法添加到豆瓣平台。如果哪位小伙伴能联系到豆瓣相关人员，可以帮忙联系下。

## 链接
* https://www.douban.com/podcast_episode/new_podcast

**Comment by stevending1st** [comment]
这是声湃的问题，正确的地址是：

https://proxy.wavpub.com/osf2f.xml

**Comment by LinuxSuRen** [comment]
好主意（虽然不知道你是怎么知道的这个地址）！已经在审核中。

**Comment by stevending1st** [comment]
> 好主意（虽然不知道你是怎么知道的这个地址）！已经在审核中。

已知其他播客的 rss 地址，替换一下路由就行。

**Comment by stevending1st** [comment]
done 

https://www.douban.com/podcast/36803294

**Comment by LinuxSuRen** [comment]
Great!
