### ISSUE TITLE
推荐看板来管理活动进程

### ISSUE THREAD

**Issue by stevending1st** [opensource-f2f/episode#27]
例如：

https://github.com/freeCodeCamp-China/activity/projects/1

**Comment by LinuxSuRen** [comment]
已经添加了 project，帮忙看看是否还有补充 https://github.com/orgs/opensource-f2f/projects/1/views/1

**Comment by stevending1st** [comment]
> 已经添加了 project，帮忙看看是否还有补充 https://github.com/orgs/opensource-f2f/projects/1/views/1

非常好🎉，如果结合 #29 效果会更好

**Comment by stevending1st** [comment]
建议将已关闭的的 Issue 也关联项目

**Comment by LinuxSuRen** [comment]
已经把嘉宾邀请相关的issue关联

**Comment by stevending1st** [comment]
突然想到，项目基建和节目录制进度建立两个看板分别管理是不是会好一些。

**Comment by LinuxSuRen** [comment]
暂时这个节目的事务还不算多，让我们先试用一段时间，然后再考虑优化如何？
