### ISSUE TITLE
推荐嘉宾 - [龙进]（个人成长系列）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#273]
### 栏目

个人成长系列

### 嘉宾名称

龙进

### GitHub

@fslongjin

### 推荐理由（着重考虑开源爱好者能收获什么）

在校期间发起 [DragonOS](https://github.com/DragonOS-Community/DragonOS)，并作为主要的 contributor。而且参与到了开源之夏活动中：

* [2024](https://summer-ospp.ac.cn/org/orgdetail/ff144b94-b2ac-42fb-8c05-c6922058cb42?lang=zh)
* [2023](https://summer-ospp.ac.cn/2023/org/orgdetail/ff144b94-b2ac-42fb-8c05-c6922058cb42?lang=zh)

### 推荐人

@HungryFish034

### note

- [ ] 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
- [ ] 可参考 [播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu) 准备好录音设备与环境。

**Comment by LinuxSuRen** [comment]
已经发送邀请 
![image](https://github.com/opensource-f2f/episode/assets/1450685/16133c78-af4b-4f0b-9c61-e71d7e93ab25)

**Comment by fslongjin** [comment]
github已接受邀请~

**Comment by LinuxSuRen** [comment]
顺利在 WSL Ubuntu 下跑起来了

![image](https://github.com/opensource-f2f/episode/assets/1450685/f67f0b2e-5e57-40a2-8fa5-dff1904ec8b2)

**Comment by LinuxSuRen** [comment]
![image](https://github.com/opensource-f2f/episode/assets/1450685/5afc9c7c-0cc4-4a7f-b20e-1f4655fe454a)

感觉上图中标记部分是个 bug？不像是一个命令行二进制文件。

另外，有个比较尴尬的问题时，没有找到 `curl`、`wget` 或其他方法来下载或安装软件。

**Comment by fslongjin** [comment]
> ![image](https://private-user-images.githubusercontent.com/1450685/325455198-5afc9c7c-0cc4-4a7f-b20e-1f4655fe454a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTM3ODYsIm5iZiI6MTcxNDAxMzQ4NiwicGF0aCI6Ii8xNDUwNjg1LzMyNTQ1NTE5OC01YWZjOWM3Yy0wY2M0LTRhN2YtYjIwZS0xZjQ2NTVmZTQ1NGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMDI1MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJjZWZhNDk3YzFiMDQyNjg3MGFlNjIyODk2MzFmMzdlYzM1ZjlhZGE4YzJiMWM4N2JkZTE5MWZiNjFlYzdjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u1GZOVjVBw_DIavpUUq1q4R6l0-hTOcTJp7AE-bhHUQ)
> 
> 感觉上图中标记部分是个 bug？不像是一个命令行二进制文件。
> 
> 另外，有个比较尴尬的问题时，没有找到 `curl`、`wget` 或其他方法来下载或安装软件。

哈哈哈，那确实是个二进制程序，是GNU core utils里面的。
确实，我赶紧整个curl或者wget上去。目前它可以用held这个编辑器来进行一些文本编辑（类似vim那样的命令）

**Comment by LinuxSuRen** [comment]
录制完成
