### ISSUE TITLE
建议使用 Github Labels 来管理 issues

### ISSUE THREAD

**Issue by stevending1st** [opensource-f2f/episode#29]
目前 issues 有很多种，建议用 Labels 进行管理，这样可以避免以后多了之后混乱。

例如：
- 项目建设
- 嘉宾推荐
- 人物访谈
...

**Comment by LinuxSuRen** [comment]
好主意，有一个 GitHub app 可以通过协作的方式来管理标签等，甚至是 repo 的描述

https://probot.github.io/apps/settings/

**Comment by stevending1st** [comment]
> @stevending1st 要不要帮忙完善下这块

抱歉，这块不太熟悉

**Comment by LinuxSuRen** [comment]
> 抱歉，这块不太熟悉

没关系，感谢关于label的建议

**Comment by stevending1st** [comment]
> 没关系，感谢关于label的建议

不用客气。
