### ISSUE TITLE
提议：为《开源面对面》创建官网

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#32]
官网可以作为一个很好的让大家了解的途径。以下是针对官网建设的大致想法（建议）：

## 技术

* Hugo 作为网站渲染的工具
* 申请一个域名
* 不依赖后端（backend），可以作为纯前端项目

## 需求

* 定制网站的首页，或者整个网站基本以一页为主来呈现主要内容
* 可以在网站上收听播客内容
* 考虑如何复用当前 repo 中的内容
* 可以展示音频的播放量
* 支持留言，可以通过 GitHub issue 获取论坛系统支持

**Comment by LinuxSuRen** [comment]
可参考的 Hugo Theme：
* https://github.com/mattstratton/castanet

**Comment by juzhiyuan** [comment]
托管在 Vercel 上，并配合 China DNS（爽歪了！）

**Comment by wey-gu** [comment]
@LinuxSuRen,

It seems https://github.com/mattstratton/castanet is a good choice while the statistic showing on the page cannot be fulfilled, if it's good to go with it I could create demos first to walkthrough configurations and designs needed to see further.

To have better statistic features, [typlog](https://typlog.com/) could be a good candidate actually.

**Comment by LinuxSuRen** [comment]
I prefer to use an open-source project. Currently, I didn't have the enough reason to pay for that.

**Comment by LinuxSuRen** [comment]
> 用 Pages + Hugo 这种静态方案呢？只需买个域名即可。

这样是可以的，甚至，在页面调试好之前都不需要买域名，可以先用 GitHub 提供的域名来用。现在确实是需要对此有兴趣的小伙伴来搞搞。

**Comment by juzhiyuan** [comment]
Check this https://www.framer.com/sites/templates/

**Comment by wey-gu** [comment]
> 用 Pages + Hugo 这种静态方案呢？只需买个域名即可。

I preferred this approach, too.

Actually my site is already quite accessible in mainland China in exactly the same stack.

www.siwei.io on vercel.

siwei.io on cf/gh pages.

**Comment by le0zh0u** [comment]
看了一下Hugo + Pages的方案，基本上可以满足需求
✅ 可以在网站上收听播客内容 [音频](https://blog.reez.me/posts/add_audio_to_hugo/)
❎ 可以展示音频的播放量
✅ 支持留言，可以通过 GitHub issue 获取论坛系统支持 - utterances

**Comment by LinuxSuRen** [comment]
个人感觉官网最主要的还是信息展示，例如：嘉宾的信息、shownotes 等等。听播客的话，相信很多人还是通过某个客户端来听的。

**Comment by MikeyWei** [comment]
我来贡献一下域名和服务器资源，有没有小伙伴能提供一下技术支持的？

**Comment by LinuxSuRen** [comment]
> 我来贡献一下域名和服务器资源，有没有小伙伴能提供一下技术支持的？

非常赞。

考虑到我们已经[发起过技术播客月](https://github.com/opensource-f2f/episode/issues/96)了，如果能再进一步的话，甚至可以考虑以技术播客共建组的名义来为技术类播客提供以下的资源：

* 域名（二级域名，或顶级域名的费用，证书等）
* 服务器
* 网站设计、维护人力资源

**Comment by MikeyWei** [comment]
> > 我来贡献一下域名和服务器资源，有没有小伙伴能提供一下技术支持的？
> 
> 非常赞。
> 
> 考虑到我们已经[发起过技术播客月](https://github.com/opensource-f2f/episode/issues/96)了，如果能再进一步的话，甚至可以考虑以技术播客共建组的名义来为技术类播客提供以下的资源：
> 
> * 域名（二级域名，或顶级域名的费用，证书等）
> * 服务器
> * 网站设计、维护人力资源

好主意，可以一步步来。先把开源面对面的官网搞一下。

**Comment by kang8** [comment]
事实上，我发现[内核恐慌](https://pan.icu/)这类(类似还有[提前怀旧](https://pretro.xyz/))的播客网站很不错，非常简约，直中要害。
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/36906329/177914238-52474c1f-5f01-4c2b-86b9-d8d973687ee4.png">

而且相对来说页面十分简单，非常好做。

或许可以先来个 figma，确定一下大致的设计。

**Comment by wey-gu** [comment]
我觉得 hugo/docusaurus 的某一个 theme 就能满足我们的要求的，不是一定需要去设计。

**Comment by kang8** [comment]
是的，hugo 的 theme 确实就能满足要求。

但看到内核恐慌的网站后觉得太棒了！除了对节目的解释外，其余就是各期的播客，可以直观的了解到该播客最近在做的事。

刚刚用 figma 大致画了一下，开源面对面做成那样的效果图：

<img width="890" alt="image" src="https://user-images.githubusercontent.com/36906329/177922897-4e8f33eb-53ee-4402-9192-545b8dc6f7d1.png">

figma link: https://www.figma.com/file/tnJqvyfu6KfBktQiZbVMTo/opensource-f2f-website-design?node-id=0%3A1

可以做个对比参考。

**Comment by zhufengme** [comment]
音播（津津乐道的内容服务品牌）这边可以为大家提供一些播客分发方面的帮助，包括：

- 基于独立域名的播客分发、数据统计
- 可以随时导出、迁移，不锁定内容的全功能音频内容托管服务
- 不仅限于RSS渠道，还包括了一些第三方渠道的分发，如车机、传统广播电台的内容授权等
- 基于本次共创的理念，这次参加技术播客月的节目我们都不向大家收取费用，并且帮助大家承担内容分发带来的流量成本
- 其他一些细节可以大家一起再完善和商议。

我们基于Web的服务预计会在10月或11月正式上线，目前是内测期间，还不能自助开通，如有需求大家可以随时联系我手工加入就可以了。

**Comment by wey-gu** [comment]
> 音播（津津乐道的内容服务品牌）这边可以为大家提供一些播客分发方面的帮助，包括：
> 
> * 基于独立域名的播客分发、数据统计
> * 可以随时导出、迁移，不锁定内容的全功能音频内容托管服务
> * 不仅限于RSS渠道，还包括了一些第三方渠道的分发，如车机、传统广播电台的内容授权等
> * 基于本次共创的理念，这次参加技术播客月的节目我们都不向大家收取费用，并且帮助大家承担内容分发带来的流量成本
> * 其他一些细节可以大家一起再完善和商议。
> 
> 我们基于Web的服务预计会在10月或11月正式上线，目前是内测期间，还不能自助开通，如有需求大家可以随时联系我手工加入就可以了。

太棒了，感谢！自建的来说最大的挑战就是统计功能比较难糊。

**Comment by MikeyWei** [comment]
不能发起投票，不知道大家对域名有什么倾向性吗？有的话请跟贴回复一下域名拼写、后缀的建议？

根据项目名字，我觉得如下2个域名拼写都还不错，后缀可选的比较多。

- opensourcef2f
- osf2f

**Comment by kang8** [comment]
可以在 Discussions 中创建一个投票。

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/36906329/178465068-9d7c56e8-1010-41ab-9b3d-8d95531ce157.png">

详情可见相关文档： https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/collaborating-with-maintainers-using-discussions#starting-a-poll 。

**Comment by kang8** [comment]
@MikeyWei 对于 opensourcef2f 和 osf2f 这样两个域名都相当不错。

对于经常使用浏览器的我来说，osf2f 这样的短域名非常适合快熟输入跳转。

而 opensourcef2f 更语义化，在文章中引用能让读者一眼读懂该链接的含义。

**Comment by MikeyWei** [comment]
> 可以在 Discussions 中创建一个投票。
> 
> <img alt="image" width="1184" src="https://user-images.githubusercontent.com/36906329/178465068-9d7c56e8-1010-41ab-9b3d-8d95531ce157.png">
> 
> 详情可见相关文档： https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/collaborating-with-maintainers-using-discussions#starting-a-poll 。

好，我得空发起个投票。

**Comment by MikeyWei** [comment]
根据大家的投票选择，购入了osf2f.net这个域名，已经在腾讯云购买了服务器。
请有意做官网制作和维护的同学联系我，添加服务器的访问权限。

**Comment by stevending1st** [comment]
> 根据大家的投票选择，购入了osf2f.net这个域名，已经在腾讯云购买了服务器。 请有意做官网制作和维护的同学联系我，添加服务器的访问权限。

建议通过 CI/CD 来处理部署，减少直接对服务器的操作。

**Comment by LinuxSuRen** [comment]
> 建议通过 CI/CD 来处理部署，减少直接对服务器的操作。

是的，网站搞好后，可以用到 GitOps 来维护。

**Comment by kang8** [comment]
@MikeyWei I can do it.

**Comment by LinuxSuRen** [comment]
> @MikeyWei I can do it.

Great! Please let us know if you have a solution for it.

**Comment by MikeyWei** [comment]
预约了一个在线会议，会议时间为本周日晚八点：2022年07月31日 20:00，入会链接 https://meeting.tencent.com/dm/IggHnvXKLiKm  （腾讯会议号：944-327-193）
请对官网制作和运维感兴趣的小伙伴届时参加一下。

主要讨论：
- 官网的内容、功能、技术栈和上线计划
- 基本的分工与协作（内容的规划、设计与前端、后端与运维）
- 域名&服务器管理权限
- 其他事项

**Comment by kang8** [comment]
> Great! Please let us know if you have a solution for it.

## 具体实现

既然是官网，那么静态网站就够用了。看到之前的讨论大致上确定了使用 [hugo](https://gohugo.io/) 来构建。但具体模版并没有确定。

@LinuxSuRen 给出 [mattstratton/castanet](https://github.com/mattstratton/castanet), [frjo/hugo-theme-zen](https://github.com/frjo/hugo-theme-zen) 和 [funkydan2/alpha-church](https://github.com/funkydan2/alpha-church) 三个模版参考。
@wey-gu 更喜欢 [mattstratton/castanet](https://github.com/mattstratton/castanet)。
但我更愿意参考 [内核恐慌](https://pan.icu/) 来自定义模版，不过这样相对来说更麻烦，得从零构建模版，还得申请模版的使用权。但我会更有动力去实现它。

具体实现，在本仓库初始化 hugo，引入模版，按照 hugo 的格式规范下目录结构，再使用 github pages 即可完成，但考虑 github 访问问题，可以使用 @juzhiyuan 提到的托管到 Vercel 上，再配合 China DNS 来解决。

可以讨论下在这个过程服务器可以帮什么忙。

## 网站页面

更具上述讨论加上我的思考，要有的页面

* 主页 – opf2f.net
* 剧集 - /S01E00-xxx - 展示每一集 shownotes 内容
* 关于 - /about - 相对于主页，进一步介绍开源面对面
* 日程 - /schedule - 展示已经确定录制时间行程安排

## 其他

对于每一集的剧集，可以使用 giscus 来利用 GitHub Discussion 来引入评论。值得注意的是，因为是利用 github 来作为评论系统，所以要想留言的前提是拥有 github 账号，不知道这会不会是一个门槛？但仔细一想开源面对面的听众应该都是 CS 从业者，应该不成问题。

**Comment by LinuxSuRen** [comment]
> 申请模版的使用权

这个大概怎么操作呢？

**Comment by kang8** [comment]
> 这个大概怎么操作呢？

可能我表达的意思不太对。内核恐慌网站风格鲜明，如果一声不吭的将其网站复刻过来总觉得不太好，所以需要给内核恐慌主播发送邮件，表明来意，询问是否可以复刻其网站样式。

内核恐慌主播们的其他播客，也是同一风格：
* [内核恐慌](https://pan.icu/)
* [疯投圈](https://crazy.capital/)
* [提前怀旧](https://pretro.xyz/)

**Comment by LinuxSuRen** [comment]
@kang8 明白了，支持+1

**Comment by LinuxSuRen** [comment]
会议纪要：
* 技术栈
  * Vercel + Hugo
* 网站需要有的内容（ 板块）
  * 除 @kang8 建议的外，提供一些统计数据
  * 关于（或其他地方）加听友互动的渠道
* 权限

Action:
* 网站建设部分，由 @kang8 和 @sxzz 推进

**Comment by MikeyWei** [comment]
> 会议纪要：
> 
> * 技术栈
>   
>   * Vercel + Hugo
> * 网站需要有的内容（ 板块）
>   
>   * 除 @kang8 建议的外，提供一些统计数据
>   * 关于（或其他地方）加听友互动的渠道
> * 权限
> 
> Action:
> 
> * 网站建设部分，由 @kang8 和 @sxzz 推进
> * @MikeyWei 设立腾讯企业邮箱

域名邮箱已开通，选择了阿里云邮箱，原因见 https://www.iplaysoft.com/free-domain-email.html
请有需要的同学找我开通所需的邮箱账号，初次登录后自行修改密码。

**Comment by sxzz** [comment]
对了，Vercel 的免费版本是不支持组织的，需要开通 $20 per user / month 的 Pro 版。
https://vercel.com/pricing

**Comment by LinuxSuRen** [comment]
@sxzz 收到。个人账号也影响不大。

**Comment by sxzz** [comment]
@LinuxSuRen 我指的是 GitHub 仓库的组织。或许也可以借助 GitHub actions 来做自动化部署。

> Error:Git repositories of GitHub organizations can only be connected to projects in Teams on Vercel. Not projects in Personal Accounts. [Learn More](https://vercel.com/docs/platform/limits#connecting-a-project-to-a-git-repository)

<img width="881" alt="image" src="https://user-images.githubusercontent.com/6481596/182364408-18c9bcc6-d26b-47bd-9566-7f885fcd6753.png">

**Comment by LinuxSuRen** [comment]
> 我指的是 GitHub 仓库的组织。或许也可以借助 GitHub actions 来做自动化部署。

意思是说，org 下的 repo 只能用 team（免费版本），对吗？那我刚才理解有误。

嗯，可以考虑用 GitHub Actions

**Comment by MikeyWei** [comment]
> @LinuxSuRen 我指的是 GitHub 仓库的组织。或许也可以借助 GitHub actions 来做自动化部署。
> 
> > Error:Git repositories of GitHub organizations can only be connected to projects in Teams on Vercel. Not projects in Personal Accounts. [Learn More](https://vercel.com/docs/platform/limits#connecting-a-project-to-a-git-repository)
> 
> <img alt="image" width="881" src="https://user-images.githubusercontent.com/6481596/182364408-18c9bcc6-d26b-47bd-9566-7f885fcd6753.png">

如果是这样，就不必用这个工具了。

**Comment by sxzz** [comment]
基于 @kang8 的 Figma 设计稿，我修改了一些样式
https://www.figma.com/file/Z24UWz9gKMvIwaBqdGBIoq/opensource-f2f-website-design-sxzz

![image](https://user-images.githubusercontent.com/6481596/183125570-5e2c8522-24f5-4890-893b-317fd977c108.png)

**Comment by sxzz** [comment]
![image](https://user-images.githubusercontent.com/6481596/183126026-9dcedd01-8ecb-4333-933a-753e9495a757.png)

另外想问问大家，左右两种样式哪种好一些？

**Comment by kang8** [comment]
> 左右两种样式哪种好一些

我更喜欢左边的样式

**Comment by wey-gu** [comment]
好棒，我也偏好左边/上边的样式哈。

**Comment by wey-gu** [comment]
footer 可以改成像这样？

> Designed & Made by 内核恐慌、Kang and sxzz with ❤️

**Comment by MikeyWei** [comment]
> ![image](https://user-images.githubusercontent.com/6481596/183126026-9dcedd01-8ecb-4333-933a-753e9495a757.png)
> 
> 另外想问问大家，左右两种样式哪种好一些？

个人更喜欢左侧的布局，视觉上结构化更清晰。
PS：对于暗夜模式，个人觉得可有可无，因为我平时不用这个模式，有点伤眼睛。

**Comment by sxzz** [comment]
> PS：对于暗夜模式，个人觉得可有可无，因为我平时不用这个模式，有点伤眼睛。

因为目前很多网站都有黑暗模式了，系统级的开关也有了。用户可以自由选择开或不开。后续如果觉得颜色不合适再调整。

**Comment by MikeyWei** [comment]
> > PS：对于暗夜模式，个人觉得可有可无，因为我平时不用这个模式，有点伤眼睛。
> 
> 因为目前很多网站都有黑暗模式了，系统级的开关也有了。用户可以自由选择开或不开。后续如果觉得颜色不合适再调整。

嗯，加个系统级开关，让用户自己选择这个方式挺好。

**Comment by MikeyWei** [comment]
ICP备案申请已通过（京ICP备2022023077号），请按照管局要求将网站备案号展示在网站首页底部，并链接到工信部首页（https://beian.miit.gov.cn/）

**Comment by sxzz** [comment]
目前部署的地址为 https://opensource-f2f.vercel.app/ （尚未开发完毕）

**Comment by sxzz** [comment]
https://vercel.com/guides/can-vercel-sponsor-my-open-source-project

是否可以找 Vercel 发封邮件赞助本项目？这样子用 Vercel 托管项目就更方便一些了

**Comment by LinuxSuRen** [comment]
> 是否可以找 Vercel 发封邮件赞助本项目？这样子用 Vercel 托管项目就更方便一些了

这是个好主意，大家可以草拟一份邮件发过去。

**Comment by sxzz** [comment]
已绑定域名 osf2f.net 速度不错

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/6481596/191867116-84ee13fa-386d-4c92-84c0-1ba643ea409a.png">

**Comment by wey-gu** [comment]
> 已绑定域名 osf2f.net 速度不错
> 
> 
> 
> <img width="1247" alt="image" src="https://user-images.githubusercontent.com/6481596/191867116-84ee13fa-386d-4c92-84c0-1ba643ea409a.png">
> 
> 

飞快

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/191871695-b1084821-d096-42a7-b215-3dd8ae7619aa.png)
这里的地址已更换

**Comment by LinuxSuRen** [comment]
> 记得在网站底部把备案信息和赞助鸣谢也加一下哈。网站上线30天内，还要去登录“全国公安机关互联网安全管理服务平台”做公安备案。

See also https://github.com/opensource-f2f/website/pull/14

**Comment by LinuxSuRen** [comment]
任何对改完整流量统计信息感兴趣、想聊天的朋友们，可以把自己的 Google 邮箱发我，把大家加进去。

**Comment by LinuxSuRen** [comment]
网站已经基本完成了主要功能，感谢每一位参与讨论、建设的朋友们！！！
