### ISSUE TITLE
推荐嘉宾 - 水歌（个人成长系列）

### ISSUE THREAD

**Issue by stevending1st** [opensource-f2f/episode#35]
GitHub: [TechQuery](https://github.com/TechQuery)
所在公司：[idea2app](https://github.com/idea2app)
岗位：全栈工程师
推荐理由：开源社区深度贡献者，开源理念积极践行者。
推荐人：stevending1st

**Comment by LinuxSuRen** [comment]
感谢推荐，如果 @TechQuery 感觉没问题的话，我们可以拉进微信群里（所有嘉宾的群）

**Comment by TechQuery** [comment]
感谢推荐，很高兴来分享开源心得，哈哈

**Comment by LinuxSuRen** [comment]
已经邀请 @TechQuery 加入《开源面对面》的 GitHub Org

**Comment by LinuxSuRen** [comment]
已经发送了 pre-talk 的会议邀请， @stevending1st 你要是有兴趣的话，可以一起来聊，下面是日历和 Google Group 的链接

* https://calendar.google.com/calendar/u/0?cid=NnYxNzcxc2w4Y2owZG9sMWxuYjRwbGJyMm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
* https://groups.google.com/g/osf2f

**Comment by LinuxSuRen** [comment]
下面是 pre-talk 的录屏资料

https://www.youtube.com/watch?v=z30ZIEYtkUk

**Comment by LinuxSuRen** [comment]
已完成
