### ISSUE TITLE
推荐嘉宾 - [Shiny-Zhu]（个人成长系列）

### ISSUE THREAD

**Issue by wey-gu** [opensource-f2f/episode#36]
GitHub: 
所在公司：Neo4j AB
岗位：developer advocate
推荐理由：朱哥和推荐人同是图技术的布道者，一直致力于在公共空间分享技术
推荐人： @wey-gu

**Comment by LinuxSuRen** [comment]
欢迎加入！

**Comment by LinuxSuRen** [comment]
pre-talk 的文档地址 https://etherpad.opendev.org/p/osf2f-talk-with-shinyzhu

**Comment by wey-gu** [comment]
The invitation was sent in calendar @shinyzhu

**Comment by LinuxSuRen** [comment]
This episode was done.
