### ISSUE TITLE
推荐嘉宾 - 小雅（个人成长）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#39]
GitHub: @xiaoya-Esther
所在公司：
岗位：
推荐理由：一开始以在校学生的身份参与到 CHAOSS China 社区，到持续参与甚至逐渐起到了 lead 作用，这对于广大在校学生来说讲会是一个非常好的激励的榜样！
推荐人：@linuxsuren

**Comment by LinuxSuRen** [comment]
已发送了 pre-talk 的邀请

**Comment by WillemJiang** [comment]
ALC Beijing也对小雅做过访谈 ，这是节目的地址 https://www.ximalaya.com/sound/382771451

**Comment by xiaoya-Esther** [comment]
https://doodle.com/meeting/participate/id/PdRjjQ0d

小伙伴们～不好意思我上次那个后来忘记选一个最终时间啦。我敲了一下下周的时间，尽可能避开大家的上班时间，麻烦各位再选一次啦，期待录制！

**Comment by LinuxSuRen** [comment]
会议邀请已经发送给 @xiaoya-Esther 和 Google Group，添加到了日历中。
