### ISSUE TITLE
提议：将 show notes 放在本仓库维护

### ISSUE THREAD

**Issue by kang8** [opensource-f2f/episode#51]
想法来自听播客过程：
> 在听 #38 时，其中提到使用 zenhub.com 管理 GitHub。因为是语音，所以并不知道具体内容，于是打开 show notes 寻找答案，花了很长时间最后在末尾找到答案。当时就在想，如果在旁边加上对应时间点就好了。首先想到的居然是提交一个 PR 😂 。当然有 PR 得先有可以改的 show notes，这就是本 issue 的缘由。

个人认为 show notes 放在 GitHub 有以下好处：

* 公开透明，所有人都可以修改，审阅。
* 不再局限于某个播客平台。
* 让听众也能参与开源。
* 版本控制。

并且 @LinuxSuRen 也提到将往期的节目也添加进来。可以参考 TiDB pingcap/tidb#26022 的做法（配套[视频](https://www.bilibili.com/video/BV1cM4y1T7D8)）：将每节目拆分成 issues，添加对应文档，标上 `good-first-issue`，让社区来维护。

**Comment by LinuxSuRen** [comment]
非常赞的想法，我们有一些还没有 shownotes，有同学帮忙整理修复后，还可以继续更新。

**Comment by stevending1st** [comment]
@kang8 我刚开始开始听，也发现了这个问题。
@LinuxSuRen 可以先将已有的 shownotes 迁移过来吗？我正在整理第零期的 shownotes

**Comment by LinuxSuRen** [comment]
> 可以先将已有的 shownotes 迁移过来吗

完全可以的。直接拷贝过来就好了。

> 我正在整理第零期的 shownotes

太赞了，先创建个 issue 跟踪下？避免和其他同学撞了。

**Comment by LinuxSuRen** [comment]
> 不知道为什么，不能选标签，也不能 Assignees 用户

可能是权限的问题，后面想下如何解决

**Comment by Mini256** [comment]
> 标上 `good-first-issue`

GitHub 官方好像认的是不带横线的 `good first issue`， 这个标签会有额外的支持，比如：在 https://github.com/explore 页面上出现。

**Comment by LinuxSuRen** [comment]
可以通过修改下面的文件添加标签

https://github.com/opensource-f2f/episode/blob/master/.github/settings.yml

欢迎帮忙补充

**Comment by LinuxSuRen** [comment]
已经有对应 PR，再次感谢 @kang8 的提议！

https://github.com/opensource-f2f/episode/pull/53
https://github.com/opensource-f2f/episode/pull/58
