### ISSUE TITLE
推荐嘉宾 - [李石亮]（个人成长）+推荐人[李梦]

### ISSUE THREAD

**Issue by LiMeng00** [opensource-f2f/episode#57]
GitHub: @teacherLeeOs
我的bilibili账号就是我的阵地，那里有我的战斗，胜过git。 https://space.bilibili.com/31272861/video 
所在公司：/
岗位：中小学社团编程老师
推荐理由：开源世界需要大理想，以及坚持实现大理想的人。
推荐人： @LiMeng00 

附推荐嘉宾自我介绍及观念：

“李石亮 38岁 大学学习的是文科，编程是个人的兴趣，对操作系统的热爱是理想。在这个领域8年了。现在正式的工作是中小学社团编程老师。自己的事业主要是培养中小学和大学生的人才。自己主要的工作内容是在学习上给他们指导，在就业和职业发展上提供思路和经验上的支持。最重要的是给他们理想，塑造他们的精神世界。让他们明白愚公移山，让他们明白敢叫日月换新天，让他们明白一万年太久，只争朝夕。

开源当然是快乐的，但在操作系统这个方向上的压力也是现实的。让年轻人明白中国的操作系统一定要在你们这代人身上实现。你就是那个时代呼唤的人。让他们在大学刚毕业就有这种天下大势，舍我取谁的气魄。这真的发生了，不是我的美好想象，我的学生大四毕业的时候就有这种气魄，我觉得很欣慰，他们没有辜负我们这些人的培养和期待，勇敢的承担起了这个责任。并且不掩饰的表达着。

关于访谈：
操作系统的落后我想我们这些老师的责任最大。企业是要面对商业竞争的。而且尤其残酷。在中国的操作系统人才的数量和质量没有超过国外的时候，我们操作系统的发展是空谈的。我们有这个使命感的人要不惜一切代价帮助，中小学生，大学生发展，而不能再等到研究生再去指导和干预。太晚了。天才是不世出的。年轻人有想法的时候要鼓励，不要告诉他搞操作系统找不到工作，要告诉他们你们先学着，我帮你们找工作。年轻人要自己写操作系统的时候不要告诉他们你写的东西没用，没有社会实用性。而是你先写着，我后面找其他的人帮你一起写。

国内操作系统企业内部也是员工之间互相竞争的，这个在某些企业是很严重的。这个是人之常情，但是我们这些不在利益系统的老师，要打破这些，尽量把linux内核相关的教程写出来，企业级别的技术写出来。要敢于自我牺牲，哪怕会造成自我的淘汰也要写出来。

我们是家国一体的，开源最后也是要为国家的独立和富强服务的。让我们尽快把开源和国家的命运绑定在一起，一起面对这些残酷的问题。开源不单单是活成自己喜欢的样子，也可以是活成国家需要的样子。”

**Comment by LinuxSuRen** [comment]
已发送加入 org 的邀请 
![Uploading image.png…]()

**Comment by LinuxSuRen** [comment]
对应的飞书文档 https://rkawrngf0e.feishu.cn/docs/doccn84Ui3bxdXn0fQWlXvlg63c#l32ucD
