### ISSUE TITLE
推荐嘉宾 - 白宦成（个人成长）

### ISSUE THREAD

**Issue by juzhiyuan** [opensource-f2f/episode#60]
GitHub: @bestony
所在公司：自由职业者（目前在 ByteDance？）
岗位：freelancer
推荐理由：2019 年认识了 小白（发现同是老乡！），喜欢折腾、有无穷无尽的主意与想法 💡 行动派！Just Google [白宦成](https://www.google.com.hk/search?q=%E7%99%BD%E5%AE%A6%E6%88%90&oq=%E7%99%BD)
推荐人：@juzhiyuan

**Comment by juzhiyuan** [comment]
已邀请 小白 入群。

**Comment by LinuxSuRen** [comment]
已经邀请进入 org 
![image](https://user-images.githubusercontent.com/1450685/156574602-7a231050-920e-4948-a383-4a503ea888c7.png)

**Comment by LinuxSuRen** [comment]
[白宦成简史](https://mp.weixin.qq.com/s/u8MJEZy-4zgEo290FUAaug)
