### ISSUE TITLE
建议：对于 shownotes 中 markdown 文件的换行格式修改

### ISSUE THREAD

**Issue by kang8** [opensource-f2f/episode#77]
在 `.md` 文件中文本之间的换行无法通过一个换行符来完成，至少需要两个换行符。另外可以通过在行尾添加两个空格来实现换行。

目前 shownotes 中 md 文件的换行就是通过行尾两个空格加上换行符来完成的。

这种方式不如两个换行符好，因为大多数的人在编辑的过程中不会关注行尾空格，当预览的时候发现没有按照自己的要求换行，只能返回文本在行尾加上两个空格。并且一般情况下行尾空格在编辑器中不会被显示出来，那就和不加空格的视觉效果是一样，这会对初学者产生困扰：明明我已经换行了，为什么在预览模式下无法换行。

使用行尾两个空格加上换行符来换行还有一个弊端，就是很容易忘记添加行尾空格。比如现在 shownotes 就存在没有加空格的例子：

https://github.com/opensource-f2f/episode/blob/dbfbb0f98fa091e20b9f18b5ff2a8de8c3209de3/shownotes/S01E07-%E9%9D%A2%E5%AF%B9%E5%BC%80%E6%94%BE%E7%9A%84%E5%A4%A7%E9%97%A8%EF%BC%8C%E6%8A%80%E6%9C%AF%E5%B0%8F%E7%99%BD%E5%8F%AF%E4%BB%A5%E4%BD%95%E7%A7%8D%E5%A7%BF%E5%8A%BF%E5%8F%82%E4%B8%8E%E5%BC%80%E6%BA%90.md?plain=1#L11-L12
https://github.com/opensource-f2f/episode/blob/dbfbb0f98fa091e20b9f18b5ff2a8de8c3209de3/shownotes/S01E08-%E5%B0%8F%E9%9B%85%EF%BC%9A%E6%88%91%E5%9C%A8%E8%AF%BB%E7%A0%94%E6%9C%9F%E9%97%B4%E5%8F%82%E4%B8%8E%20CHAOSS%20%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA%E7%9A%84%E5%BF%83%E8%B7%AF%E7%BB%8F%E5%8E%86.md?plain=1#L13

所以我建议使用两个换行符在纯文本之间的换行。

另外对于 shownotes 中的 **时间线** 和 **拓展阅读** 模块，可以换成列表形式展示，这样就省去了换行符的困恼，而且也更统一。

**Comment by LinuxSuRen** [comment]
同意，shownotes 主要就是 时间线 和 拓展阅读 模块
