### ISSUE TITLE
推荐嘉宾 - [tison]（个人成长系列）

### ISSUE THREAD

**Issue by wey-gu** [opensource-f2f/episode#86]
GitHub（可选）：[@tisonkun](https://github.com/tisonkun) @tisonkun
所在公司/岗位（可选）：
Twitter（可选）：https://twitter.com/tison1096
博客地址（或其他媒体平台）（可选）：https://tisonkun.org/
推荐理由：Tison 是一位年轻的开源领袖、modern wizard、Apache Memeber、在很多开源项目中有长期重要的贡献。可贵的是，Tison 也善于对思考进行系统整理和输出，我总能从他的表达和思辨中获得深刻启发。
推荐人：@wey-gu

建议嘉宾[订阅《开源面对面》的邮件列表](mailto:jenkinsci-users+subscribe@googlegroups.com)，方便后续发送录制的会议邀请。

**Comment by majinghe** [comment]
期待 tison 这一期。

**Comment by LinuxSuRen** [comment]
这里有提到 tison 参与开源的一些经历 https://mp.weixin.qq.com/s/216JPH-3Hv0KVmS7fzycNg

**Comment by LinuxSuRen** [comment]
文档地址 https://rkawrngf0e.feishu.cn/docs/doccnnA5vWDI8C55ZagWZy0jLnd

**Comment by LinuxSuRen** [comment]
pre-talk 时间：9月17日，下午2点半

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/KxHykaM4LwTs
