### ISSUE TITLE
建议：将嘉宾推荐内容直接在喜马拉雅的详情中列出来

### ISSUE THREAD

**Issue by fanfan50** [opensource-f2f/episode#88]
比如YiHong老师推荐的文章，People Die, but Long Live GitHub。听了几遍，没听明白。另外，听的时候在路上，查找文章的时候还需要返回去重新去听原来的内容，非常浪费时间。望采纳，谢谢！

**Comment by LinuxSuRen** [comment]
感谢 @fanfan50 反馈意见，赞！
有其他没听清楚的英文或者词汇的话，可以给 @wey-gu @yihong0618 在这里留言。

**Comment by kang8** [comment]
@fanfan50 感谢意见！

事实上，在本仓库中维护了每一期的 [shownotes](https://github.com/opensource-f2f/episode/tree/master/shownotes)，在里面可以看到每一期节目的内容（虽然现在看来不是很详细，也欢迎听众贡献完善）

比如 YiHong 这一期，在 shownotes 中是有 People Die, but Long Live GitHub 对应的链接：
https://github.com/opensource-f2f/episode/blob/1a37a3bc4bd4040217d8b51ebd3a82fed3ccd78e/shownotes/S01E03-%E4%B8%93%E8%AE%BFYihong-%E8%87%AA%E5%AD%A6%E6%88%90%E4%B8%BA%E6%B5%81%E8%A1%8C%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE%E4%BD%9C%E8%80%85%E7%9A%84%E7%82%B9%E6%BB%B4.md?plain=1#L46

对于其他平台，由于同步，审核或遗忘可能导致未及时更新（现在喜马拉雅是同步的）。

再次感谢宝贵的意见，如果其他问题也欢迎一并提出。

**Comment by LinuxSuRen** [comment]
不完善的 shownotes 都可以通过提交 PR 的方式来完善，之后会更新。

**Comment by wey-gu** [comment]
> 比如YiHong老师推荐的文章，People Die, but Long Live GitHub。听了几遍，没听明白。另外，听的时候在路上，查找文章的时候还需要返回去重新去听原来的内容，非常浪费时间。望采纳，谢谢！

诶，给自己一拳，我才看到您的建议，以后我们会花更多时间弄弄好 show notes，否则会给大家带来很多烦恼。

在时间戳里增加扩展阅读的序号可能会更好的避免这样情况？
@fanfan50 @kang8 @LinuxSuRen

**Comment by LinuxSuRen** [comment]
> 在时间戳里增加扩展阅读的序号可能会更好的避免这样情况？

这样的话，肯定会更好了，不过，这个还是要看整理 shownotes 人的时间、精力。而且，shownotes 也是可以“迭代”起来的。
