### ISSUE TITLE
推荐嘉宾 - 嵇斌（个人成长系列）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#90]
GitHub（可选）：@matrixji
所在公司/岗位（可选）：
Twitter（可选）：[@matrixji](https://twitter.com/matrixji)
博客地址（或其他媒体平台）（可选）：https://mp.weixin.qq.com/s/Jnf2rW4WZDvqCys0np0M9g
推荐理由：非常认同 @matrixji 在[《Milvus Committer 嵇斌：参与开源是一种对自己的投资》](https://mp.weixin.qq.com/s/Jnf2rW4WZDvqCys0np0M9g)中表达的观点“为了要破局、寻求更高效的学习方法”
推荐人：@linuxsuren

再次，我也非常感谢 Zilliz 发现并帮助宣传开源人 @matrixji

建议嘉宾[订阅《开源面对面》的邮件列表](mailto:jenkinsci-users+subscribe@googlegroups.com)，方便后续发送录制的会议邀请。

**Comment by LinuxSuRen** [comment]
文档链接 https://rkawrngf0e.feishu.cn/docs/doccnla6ZxqGyw8L8PmZ9VdiOwe

**Comment by LinuxSuRen** [comment]
@Hera-han 欢迎，上面的链接中有会议地址、时间

**Comment by matrixji** [comment]
> 我和思为可以参加录制吗？本来之前也想约嵇斌大神的
荣幸，已经有点期待思为的声音了 :-)

**Comment by LinuxSuRen** [comment]
正式录制会议链接 https://meeting.tencent.com/dm/btYOk2MiQhPB
