### ISSUE TITLE
推荐嘉宾 - [Sonic 云真机测试平台]（开源项目）

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#91]
GitHub（可选）：@SonicCloudOrg @ZhouYixun
所在公司/岗位（可选）：
Twitter（可选）：
博客地址（或其他媒体平台）（可选）：
推荐理由：Sonic 云真机测试平台是由个人发起并运营的开源项目，能在国内持续保持初心做开源项目的每一位开源作者都值得我们尊重，而《开源面对面》正希望能为这些还没有到了“大红大紫”状态的开源项目和开源人发声。
推荐人：@linuxsuren
脚本地址：https://rkawrngf0e.feishu.cn/docs/doccnu3S5XE0TAk11cN5CXfJlYg

@ZhouYixun，欢迎邀请你们团队的人一起来分享下你们的开源项目。可以考虑分别邀请从头开始参与、半路加入、新加入不久的 contributor 一起来聊，这样可以从多角度来分享你们项目的点点滴滴。

建议嘉宾[订阅《开源面对面》的邮件列表](mailto:jenkinsci-users+subscribe@googlegroups.com)，方便后续发送录制的会议邀请。

**Comment by ZhouYixun** [comment]
暂时我们时间安排不上，后续再继续合作哦~

**Comment by LinuxSuRen** [comment]
期待后续 @ZhouYixun 方便的时候来录制节目，那我就暂时关闭这个 issue 了

**Comment by ZhouYixun** [comment]
近期时间不太方便，想离开好好沉淀，非常感谢Rick的邀请~

**Comment by LinuxSuRen** [comment]
经 @ZhouYixun 的要求，现移除 @ZhouYixun 

![image](https://user-images.githubusercontent.com/1450685/210313840-88979c54-8cc7-41f5-bf49-38ab1d5213b2.png)

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/210313875-8e37ee5f-e8d8-4192-9f3a-8d4fd5d1d4ce.png)
