### ISSUE TITLE
提议：联合多个技术类播客节目推广

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/episode#96]
该提议后续的文案更新主要在 https://rkawrngf0e.feishu.cn/docs/doccn8ojRP78eFvN5XQAp8gd1Eh

从大家的感受和日常观察中可以看到，播客在国内的技术圈里还是一个相对小众的内容输出平台。虽然播客相比视频、文字有一些不足，但音频本身不需要听众大部分注意力等优势，也是值得我们来推广的。

如果您（或者身边的朋友）在制作（或想要）播客，而且希望让自己的播客节目受到更多人的关注，那欢迎继续阅读。

假如你的播客节目有干货，但依然没有理想的听众群体，那么我们可以携手“出圈”。人多力量大，开源共建是我们的主题！

有两个思路：长期路线、短期突破。

### 长期路线
从长期来讲，有意愿共建的“播客主持人”们可以发起一个“技术播客节”（或类似的形式，技术播客联盟？），定期组织一些活动来普及、推广技术类播客。那么大家可以在这些活动上收获哪些呢？

- 作为听众，了解有哪些风格、主题的播客
- 作为制作方，集中、公开宣传自己节目的特点、亮点
- 作为制作方，和其他节目制作方交流心得体会、经验
- 作为制作方，集中式地可以收到听众的直接反馈
- 作为制作方，做播客不再寂寞，让越来越多地人开始关注、了解播客，让国内的技术播客领域更加专业、活跃

### 短期突破
和长期路线相同地，大家可以联合起来通过一场直播来宣传播客、讨论等等。与之不同的是，这个短期的形式下，大家不需要成立一个新的组织，相对简单一些。

### 合作内容
首先，我们可以收集对该提议有兴趣的制作方，根据数量来确定进一步的形式。如果参与者相对较少（例如5个以内），可以来一场直播大家分别聊聊以下提供参考的话题：

- 大家做播客的初衷，现状以及未来计划（如果有的话）的介绍
- 制作团队成员的故事、观点分享
- 我们为什么需要听播客，从中可以有哪些收获（知识、行业背景、观点分享等等）
- 制作经验分享（可能是一个制作团队之间更感兴趣的话，可以考虑作为一个单独的活动）
- 听友互动

### 潜在合作的播客
- ALC Beijing
- 大话开源
- Nebula Graph 星球
- 迪魔王 Devmore
- 开源之道Talking
- CHAOSScast China
- The Data Way
- Web Worker
- 科技零食
- Go 夜聊
- 编码人声
- ByteTalk
- OnBoard
- 开源社
- TBD

> 未完成，待继续
> 以上大部分内容来自于《开源面对面》嘉宾群讨论

<img width="300px" src="https://user-images.githubusercontent.com/1450685/167235357-dbdbcbd0-03e9-462d-8cd0-342b2c3b622d.png"/>

**Comment by majinghe** [comment]
OpenTEKr 也应该算一个。

**Comment by Otto-J** [comment]
可以啊， web worker 可以来串台

**Comment by wey-gu** [comment]
Nebula Graph 星球 @Hera-han 也来串台哈

**Comment by juzhiyuan** [comment]
@bestony 编码人声 😄

**Comment by Ifsoboy00** [comment]
科技零食也可以来串台hh

**Comment by juzhiyuan** [comment]
And OnBoard!

**Comment by juzhiyuan** [comment]
@LinuxSuRen 安利一期 Podcast：https://www.xiaoyuzhoufm.com/episode/6254449078c521d9e8111225

**Comment by WillemJiang** [comment]
+1 可以采用直播的方式和听友交互起来。

**Comment by LinuxSuRen** [comment]
第一次沟通交流会议，回放地址 https://www.bilibili.com/video/BV1sY4y1r75r

**Comment by miyaliu666** [comment]
我手机上最近没有装飞书，没法登录在飞书文档里编辑，所以就在这里写点零星想法。

我之前参与了《开源面对面》一期节目的录制，主要是向听众传达——即便是背景很普通的非技术专业的人，也能参与开源，并且通过开源实现自身价值。下面的想法是基于这期节目的复盘，从听众参与、分享以及推动听众行动的角度来说，这些方式也都有利于栏目推广。以后咱们其他期节目以及这次联合推广也可以参考~

### 参与

- 我在录节目之前写过一篇文章，可以提前发到听友群（当时好像还没有）或者是朋友圈之类的 搜集听众的问题，在播客中增加一个回答听众问题的环节，被选中问题的听众可以获得某种形式的感谢。

- 可以在节目末尾面向听友提一个问题，把答案发给公众号后台，回答正确的获得抽奖链接，我可以提供几个背包作为奖品。

### 分享

得到、微信读书等等 app 有一个很好的功能是 读者可以摘取某一段话，发带有二维码的图片到朋友圈，这是一种很好的方式，分享的同时也体现读者自己的立场、认知。播客在这个方面具有天然的弱势，那么我们可以把嘉宾的一些金句做成图片，同样带有二维码，放在节目的文字摘要里面（不知道喜马拉雅、小宇宙......是否支持上传图片），也发到听友群，便于听友分享。

### 推动听众的行动

我们做那一个系列的节目的主要目的是 希望听众受到鼓励之后，真的来了解、参与我们的开源项目。但是可能很多人不会真的去 GitHub 搜索我们的仓库，特别是那些完全没有经验的人，一打开 GitHub，看不懂，可能就被劝退了。到目前为止，我的那期节目在喜马拉雅的收听量是 3000 多，但是还没有新的志愿者是因为收听了这期播客来联系我 - 文字摘要里面也没有留我的联系方式，我也没有进听友群，是原因之一 - 大家觉得这个情况需要改善吗？

比如，做一个文档放在哪儿，包含两个信息：参与过这个系列的嘉宾 所在的开源社区的贡献指南链接，嘉宾的联系方式。

### 本次技术播客节的环节（或者叫技术播客月，持续一个月的活动）
- 各个播客的主理人/主持人们除了一起直播，还可以两两互相采访
- 往期嘉宾返场，一起做一次直播
- ......暂时没想到别的环节

前面提到的听友参与方式，也可以用在这里。奖品最好是有一定吸引力的。

开源社之前做了个海报生成器，我们可以 fork 来改改，把联合的播客、活动日程这些主要信息写上，然后所有嘉宾或听友都可以自主加上个人信息去分享宣传，比如：昵称、一句话描述自己、喜欢哪个播客节目的什么方面、在什么时候听播客、获得了什么......如果要向一位朋友推荐播客，你会怎么推荐 就怎么写。

**Comment by LinuxSuRen** [comment]
非常感谢 @miyaliu666 的深度反馈！！！

> 把嘉宾的一些金句做成图片，同样带有二维码

这个建议非常好，要是能找到一个简单易用的工具，或者对作图比较擅长的同学来帮忙的话，是非常赞的！

> 但是还没有新的志愿者是因为收听了这期播客来联系我 - 文字摘要里面也没有留我的联系方式，我也没有进听友群，是原因之一 - 大家觉得这个情况需要改善吗

我们的 shownotes 在这方面需要改进，不过，[已经发布的 notes](https://github.com/opensource-f2f/episode/blob/master/shownotes/S01E04-Miya%E7%9A%84%E6%95%85%E4%BA%8B-%E4%BB%8E%E5%B7%A5%E5%9C%B0%E6%89%93%E5%8D%B0%E5%B0%8F%E5%A6%B9%E5%88%B0%E5%85%A8%E7%90%83%E7%9F%A5%E5%90%8D%E6%95%99%E8%82%B2%E5%85%AC%E7%9B%8A%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA%E5%A4%A7%E4%BD%BF.md) 依然是可以修改的。可以考虑帮忙提供一些信息，然后更新到喜马拉雅中。

> 开源社之前做了个海报生成器，我们可以 fork 来改改，把联合的播客、活动日程这些主要信息写

这个也很赞。链接在这里 https://github.com/Ovilia/acasia-poster

**Comment by LinuxSuRen** [comment]
本次活动的文案初稿，请给位查收 https://rkawrngf0e.feishu.cn/docs/doccnYulyRBOJp6PbXbph8X7vlc

**Comment by LinuxSuRen** [comment]
各位同学，期待5月15日（周日）晚8点与各位一起讨论、共建技术播客月活动
点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/X6muQRTSVlDZ

**Comment by juzhiyuan** [comment]
🤣 我们每周日同一时间有例会，还请整理下会议记录。

**Comment by LinuxSuRen** [comment]
> 

好的，会有文字、录屏记录。

**Comment by LinuxSuRen** [comment]
第二次讨论，视频会议回放 https://www.bilibili.com/video/BV1B34y1h7Rb

**Comment by LinuxSuRen** [comment]
相关文档汇总：
* https://rkawrngf0e.feishu.cn/sheets/shtcnMojooVWy9qxVKzgRHV57je
* https://rkawrngf0e.feishu.cn/docs/doccn8R6xBVrcHMVYiVgq4Rds7d
* https://rkawrngf0e.feishu.cn/docs/doccnYulyRBOJp6PbXbph8X7vlc
* https://rkawrngf0e.feishu.cn/docs/doccn8ojRP78eFvN5XQAp8gd1Eh

**Comment by le0zh0u** [comment]
> 相关文档汇总：
> 
> * https://rkawrngf0e.feishu.cn/sheets/shtcnMojooVWy9qxVKzgRHV57je
议题征集表格

> * https://rkawrngf0e.feishu.cn/docs/doccn8R6xBVrcHMVYiVgq4Rds7d
邀请函

> * https://rkawrngf0e.feishu.cn/docs/doccnYulyRBOJp6PbXbph8X7vlc
技术播客月 - 2022

> * https://rkawrngf0e.feishu.cn/docs/doccn8ojRP78eFvN5XQAp8gd1Eh
联合多个技术类播客节目推广

**Comment by zhufengme** [comment]
除了《编码人声》外，津津乐道播客网络也愿意参与进来，帮助大家做一些流量曝光、平台合作、增长等方面的支持工作。目前可以想到的着手点和资源梳理如下：

- 对活动的口播宣传，我们在所有旗下节目中给这次播客月活动做一次贴片广告的口播，吸引更多人来关注技术领域的专业表达
- 曝光和增长支持，除了录制播客月的节目外，我们还可以请各位友台的主播来《科技乱炖》节目，结合当期话题作为嘉宾一起来录制节目，并推广自己的节目
- 服务支持，我们旗下的服务品牌“[音播](https://wavpub.com)”可以为所有加入播客月的节目免费提供播客托管、数据分析方面的服务
- 未来的一些变现可能，我们不定期的有些专业领域的广告投放，可以视情况提供给大家一些可能的商业机会。

无论如何，这个播客月是个特别棒的想法，我们愿意提供所有可能的支持，也愿意更多的参与进来。

**Comment by LinuxSuRen** [comment]
hi @zhufengme 非常欢迎加入我们，以及对本次活动的支持。可以考虑下面的点：

- 请《科技乱炖》的主播添加交流议题到[这个文档](https://rkawrngf0e.feishu.cn/sheets/shtcnMojooVWy9qxVKzgRHV57je)
- 津津乐道播客网络作为本次活动的合作宣传，提交 logo 到 https://github.com/opensource-f2f/partner

**Comment by LinuxSuRen** [comment]
活动整体的时间线 https://rkawrngf0e.feishu.cn/docs/doccncM19hnU7sahjmXuxtdf4Kh

**Comment by LinuxSuRen** [comment]
活动已结束，非常感谢各位，共建者的付出，希望每一位都有收获！！！

期待对该活动感兴趣的朋友们参与活动复盘会

https://rkawrngf0e.feishu.cn/docx/doxcnR5iwEfoF58ZSYtBZBajG7c

**Comment by LinuxSuRen** [comment]
* 礼品派送抽奖录屏 https://www.bilibili.com/video/BV1HU4y1q7xz
* 复盘会 https://www.bilibili.com/video/BV17V4y1773i
