### ISSUE TITLE
推荐嘉宾 - 三咲智子（个人成长系列）

### ISSUE THREAD

**Issue by stevending1st** [opensource-f2f/episode#98]
GitHub（可选）：@sxzz
所在公司/岗位（可选）：@element-plus
Twitter（可选）：https://twitter.com/sanxiaozhizi
博客地址（或其他媒体平台）（可选）：https://blog.sxzz.moe/
推荐理由：学生开源参与者，已经成为国内广泛使用的开源框架的维护者。
推荐人：@stevending1st

建议嘉宾[订阅《开源面对面》的邮件列表](mailto:jenkinsci-users+subscribe@googlegroups.com)，方便后续发送录制的会议邀请。

**Comment by ShenQingchuan** [comment]
前来为智子打 Call ！

**Comment by wey-gu** [comment]
wow 👍🏻！！！

**Comment by Magren0321** [comment]
👍🏻！！

**Comment by zouhangwithsweet** [comment]
💯

**Comment by emojiiii** [comment]
💯

**Comment by LinuxSuRen** [comment]
羡慕 @sxzz 有这么多粉丝、小伙伴！！！

**Comment by sxzz** [comment]
@LinuxSuRen 哈哈哈，都是 Element Plus 和即刻认识的～

**Comment by LinuxSuRen** [comment]
已经发送加入该 org 的邀请 
![image](https://user-images.githubusercontent.com/1450685/167777630-9569c4c5-e47d-4b50-bdff-452ac5bb582d.png)

**Comment by LinuxSuRen** [comment]
近期准备采访 @sxzz ，文档为 https://rkawrngf0e.feishu.cn/docs/doccn3g18OdGpJjl5bLYhmX74Xd

**Comment by LinuxSuRen** [comment]
pre-talk 会议时间：22-08-26
地址：https://meeting.tencent.com/dm/cHQzi22X4IJP
